In [2]:
import pandas as pd

df1 = pd.read_csv("../../02_Data/raw/gamefound_ALL_comments_Hierarchical.csv")
df2 = pd.read_csv("../../02_Data/raw/gamefound_comments_original.csv")

In [20]:
df3 = pd.read_csv("../../02_Data/raw/gamefound_list.csv")

In [ ]:
c_list = ['project_name', 'comment_id', 'parent_id', 'depth_level', 'author_id',
       'author_name', 'creator_id', 'is_pledge_master', 'is_backer',
       'is_prior_backer', 'is_pathfinder', 'has_children',
       'children_count', 'text', 'created_at', 'likes']

,project_name,comment_id,parent_id,depth_level,author_id,author_name,creator_id,is_pledge_master,is_backer,backer_number,is_prior_backer,is_pathfinder,has_children,children_count,text,created_at,likes
0,Stonesaga Second Printing,2598484,NaN,0,244541,BrendanMcCaskell,1,False,False,NaN,False,False,False,0,Funded! Let's keep it going!,2026-05-26T15:30:56.06Z,11
1,Stonesaga Second Printing,2611664,NaN,0,1378081,Mathias_VN,0,False,False,NaN,False,False,True,1,Since I didn’t own the previous version of Sto...,2026-06-01T18:14:19.01Z,0
2,Stonesaga Second Printing,2611763,2611664.0,1,1359539,mightygoat,0,False,True,779.0,True,False,False,0,You wouldn't need the ERRATA pack. The rechar...,2026-06-01T19:11:00.073Z,0
3,Stonesaga Second Printing,2611527,NaN,0,1913147,Clavagan,0,False,False,NaN,False,False,False,0,Esiste anche con traduzione italiana?,2026-06-01T16:55:25.363Z,0
4,Stonesaga Second Printing,2609072,NaN,0,515392,Remo,0,True,True,606.0,True,False,True,6,Shouldnt Errata pack include a free journal bo...,2026-05-31T04:51:54.227Z,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1585624,Goldenstar: The Galactic Tournament,115587,115520.0,1,64315,Darken,1,False,False,NaN,False,False,False,0,"You start with cards from both Characters, but...",2021-09-21T19:19:50.52Z,0
1585625,Goldenstar: The Galactic Tournament,115489,NaN,0,246326,Basti,0,True,False,NaN,False,False,True,1,Is there a possibility for a german version of...,2021-09-21T17:42:03.717Z,1
1585626,Goldenstar: The Galactic Tournament,118641,115489.0,1,178062,Piotr_Gindi,0,False,False,NaN,False,False,False,0,Unfortunately not at the moment :/,2021-09-28T08:59:12.633Z,0
1585627,Goldenstar: The Galactic Tournament,115326,NaN,0,130137,BigBenMagnus,0,False,False,NaN,False,False,True,1,Do you plan to make a miniature only pledge ?,2021-09-21T13:28:30.39Z,0
1585628,Goldenstar: The Galactic Tournament,115344,115326.0,1,64315,Darken,1,False,False,NaN,False,False,False,0,"Unfortunately no, but if there will be a massi...",2021-09-21T14:10:21.233Z,0

In [4]:
df2

,project_url,comment_thread_id,comment_id,parent_id,author_id,author_type,is_creator,comment_text,likes_count,created_at,edited_at,children_total_count,children,raw_comment
0,https://gamefound.com:443/en/projects/oomm-gam...,75760,2598484,NaN,244541,1,True,Funded! Let's keep it going!,11,2026-05-26T15:30:56.06Z,NaN,0,[],"{'authorID': 244541, 'authorType': 1, 'childre..."
1,https://gamefound.com:443/en/projects/oomm-gam...,75760,2609072,NaN,515392,0,False,Shouldnt Errata pack include a free journal bo...,0,2026-05-31T04:51:54.227Z,NaN,5,"[{'authorID': 1359539, 'authorType': 0, 'child...","{'authorID': 515392, 'authorType': 0, 'childre..."
2,https://gamefound.com:443/en/projects/oomm-gam...,75760,2608998,NaN,1217273,0,False,Would it be possible to hire an external ruleb...,0,2026-05-31T01:41:22.533Z,NaN,1,"[{'authorID': 244541, 'authorType': 1, 'childr...","{'authorID': 1217273, 'authorType': 0, 'childr..."
3,https://gamefound.com:443/en/projects/oomm-gam...,75760,2608134,NaN,23628,0,False,Is it possible to send the upgrade pack sooner??,0,2026-05-30T10:53:21.483Z,NaN,4,"[{'authorID': 2092016, 'authorType': 1, 'child...","{'authorID': 23628, 'authorType': 0, 'children..."
4,https://gamefound.com:443/en/projects/oomm-gam...,75760,2608131,NaN,1350975,0,False,"Attendez sa sortie en boutique, ça vaut mieux....",0,2026-05-30T10:52:49.09Z,NaN,4,"[{'authorID': 1350975, 'authorType': 0, 'child...","{'authorID': 1350975, 'authorType': 0, 'childr..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
677658,https://gamefound.com:443/en/projects/gindi/go...,2581,115784,NaN,635,0,False,@Darken - I don’t want to be the grammar polic...,1,2021-09-22T01:06:50.077Z,NaN,3,"[{'authorID': 64315, 'authorType': 1, 'childre...","{'authorID': 635, 'authorType': 0, 'children':..."
677659,https://gamefound.com:443/en/projects/gindi/go...,2581,115548,NaN,2735,0,False,I absolutely adore enchanters and will forever...,1,2021-09-21T18:28:59.853Z,2021-09-21T18:31:55.933Z,2,"[{'authorID': 64315, 'authorType': 1, 'childre...","{'authorID': 2735, 'authorType': 0, 'children'..."
677660,https://gamefound.com:443/en/projects/gindi/go...,2581,115520,NaN,346737,0,False,So the deck building aspect is just taking the...,0,2021-09-21T18:12:42.863Z,NaN,1,"[{'authorID': 64315, 'authorType': 1, 'childre...","{'authorID': 346737, 'authorType': 0, 'childre..."
677661,https://gamefound.com:443/en/projects/gindi/go...,2581,115489,NaN,246326,0,False,Is there a possibility for a german version of...,1,2021-09-21T17:42:03.717Z,NaN,1,"[{'authorID': 178062, 'authorType': 0, 'childr...","{'authorID': 246326, 'authorType': 0, 'childre..."
677662,https://gamefound.com:443/en/projects/gindi/go...,2581,115326,NaN,130137,0,False,Do you plan to make a miniature only pledge ?,0,2021-09-21T13:28:30.39Z,NaN,1,"[{'authorID': 64315, 'authorType': 1, 'childre...","{'authorID': 130137, 'authorType': 0, 'childre..."

In [13]:
df2["raw_comment"][0]

'{\'authorID\': 244541, \'authorType\': 1, \'children\': [], \'childrenTotalCount\': 0, \'commentID\': 2598484, \'commentThreadID\': 75760, \'createdAt\': \'2026-05-26T15:30:56.06Z\', \'editedAt\': None, \'isDeleted\': False, \'isHidden\': False, \'isReportedByCreator\': False, \'likesCount\': 11, \'newerChildrenCount\': 0, \'newRepliesCount\': 0, \'parentID\': None, \'pinnedAt\': \'2026-05-26T15:30:58.357Z\', \'text\': "Funded! Let\'s keep it going!", \'userComment\': None}'

In [9]:
df2["children_total_count"].sum()

1291028

In [11]:
df1['project_name'].unique()

array(['Stonesaga Second Printing', 'Beast: Ashfall',
       'Capitals of Tactoria', ..., 'PACHAMAMA',
       'Taverns & Dragons (Canceled)',
       'Goldenstar: The Galactic Tournament'], dtype=object)

In [14]:
df2['project_url']

0         https://gamefound.com:443/en/projects/oomm-gam...
1         https://gamefound.com:443/en/projects/oomm-gam...
2         https://gamefound.com:443/en/projects/oomm-gam...
3         https://gamefound.com:443/en/projects/oomm-gam...
4         https://gamefound.com:443/en/projects/oomm-gam...
                                ...
677658    https://gamefound.com:443/en/projects/gindi/go...
677659    https://gamefound.com:443/en/projects/gindi/go...
677660    https://gamefound.com:443/en/projects/gindi/go...
677661    https://gamefound.com:443/en/projects/gindi/go...
677662    https://gamefound.com:443/en/projects/gindi/go...
Name: project_url, Length: 677663, dtype: object

In [22]:
df3["name"]

0                                Bloodstone
1                                    Aeolis
2                                    A Life
3             Growing Season Deluxe Edition
4                 Stonesaga Second Printing
                       ...
2585      Spring and Autumn: Story of China
2586         Crossroads Inn: The Board Game
2587                              PACHAMAMA
2588           Taverns & Dragons (Canceled)
2589    Goldenstar: The Galactic Tournament
Name: name, Length: 2590, dtype: object

In [37]:
from tqdm.notebook import tqdm

empty_list =[]
for i in tqdm(df3['name']):
    if i not in df1['project_name'].unique():
        empty_list.append(i)

  0%|          | 0/2590 [00:00<?, ?it/s]

In [46]:
df3.columns

Index(['Unnamed: 0', 'name', 'creator', 'currencySymbol', 'campaignGoal',
       'fundsGathered', 'backersCount', 'campaignStart', 'campaignEnd',
       'description', 'project_url', 'phaseLabel', 'enableBoardGameProperties',
       'minPlayers', 'maxPlayers', 'minAge', 'playTime', 'playTimeDescription',
       'playTimeUnit', 'pledgeManagerAvailability', 'fundedInSeconds',
       'imageUrl', 'pledgeManagerSoftCloseDeadline', 'projectTags',
       'enableShippingOnlyMode', 'originalType'],
      dtype='object')

In [56]:
df3.loc[df3['name'].isin(empty_list),'phaseLabel'].value_counts()

Pledge manager - Closed          298
Store                             42
Upcoming                          23
Crowdfunding - Unsuccessful        5
Pledge manager - Open for all      3
Pledge manager - Limited           3
Late Pledge - Open for all         2
Crowdfunding - Funded              1
Name: phaseLabel, dtype: int64

In [58]:
df3['phaseLabel'].value_counts()

Pledge manager - Closed          1286
Upcoming                          394
Pledge manager - Limited          220
Pledge manager - Open for all     183
Crowdfunding - Canceled           136
Crowdfunding - Unsuccessful       124
Late Pledge - Open for all         99
Crowdfunding - Funded              43
Store                              42
Crowdfunding                       39
Preorder                           22
Express crowdfunding                1
Late Pledge - Ended                 1
Name: phaseLabel, dtype: int64

In [65]:
df3.loc[df3['name'].isin(empty_list) & (df3['phaseLabel'] == 'Pledge manager - Closed')]

,Unnamed: 0,name,creator,currencySymbol,campaignGoal,fundsGathered,backersCount,campaignStart,campaignEnd,description,...,playTime,playTimeDescription,playTimeUnit,pledgeManagerAvailability,fundedInSeconds,imageUrl,pledgeManagerSoftCloseDeadline,projectTags,enableShippingOnlyMode,originalType
811,811,Christmas Union,Playful Anarchy (Fagner Lima),€,1500.0,1553.03,54,2025-12-10T15:10:00Z,2025-12-20T21:00:00Z,Christmas time is coming and as ALWAYS Santa C...,...,30.0,NaN,0,2.0,724894,https://imgcdn.gamefound.com/projectimage/proj...,2026-04-29T22:00:00Z,"[{'projectTagID': 21, 'isSystem': False, 'isVi...",False,1
1119,1119,Four Forests,Gold Seal Games,$,NaN,8284.22,273,NaN,NaN,Cultivate your forest to attract the most pres...,...,30.0,NaN,0,2.0,0,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-11T14:00:00Z,"[{'projectTagID': 1, 'isSystem': False, 'isVis...",False,0
1160,1160,Mad Match-Up,UNDERTREEGAMES,$,NaN,2711.23,87,NaN,NaN,"Welcome to Mad Match-Up, Mad Match-Up is a fas...",...,20.0,NaN,0,2.0,0,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-13T20:00:00Z,"[{'projectTagID': 2, 'isSystem': False, 'isVis...",False,0
1224,1224,Imperial Twing,Emperor Claudius,Fr.,NaN,5678.29,97,NaN,NaN,"Imperial Twing is a fast-paced, tactical card ...",...,60.0,NaN,0,2.0,0,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-09T20:00:00Z,"[{'projectTagID': 2, 'isSystem': False, 'isVis...",False,0
1310,1310,Naughty or Nice,Bunnyhog Games,£,NaN,7057.26,123,NaN,NaN,A light-euro set collection game about gift gi...,...,30.0,NaN,0,2.0,0,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-14T03:00:00Z,"[{'projectTagID': 2, 'isSystem': False, 'isVis...",False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2281,2281,GKR: Heavy Hitters,Weta Workshop,$,NaN,0.00,0,NaN,NaN,"The near-future is here, and Earth’s abandoned...",...,NaN,NaN,0,2.0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"[{'projectTagID': 11, 'isSystem': False, 'isVi...",True,0
2282,2282,Endure The Stars,Grimlord Games,£,NaN,0.00,0,NaN,NaN,An epic 1-6 player Sci-Fi co-op fight for surv...,...,NaN,NaN,0,2.0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"[{'projectTagID': 8, 'isSystem': False, 'isVis...",True,0
2283,2283,Star Scrappers: Cave-In,Hexy Studio,$,NaN,0.00,0,NaN,NaN,"Become a galactic entrepreneur, a ruthless min...",...,NaN,NaN,0,2.0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"[{'projectTagID': 2, 'isSystem': False, 'isVis...",True,0
2284,2284,Board&Dice,Board&Dice,$,NaN,0.00,0,NaN,NaN,"Board&Dice designs, develops, and publishes fa...",...,NaN,NaN,0,2.0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"[{'projectTagID': 3, 'isSystem': False, 'isVis...",True,0
2285,2285,BATTALIA: The Stormgates,Fantasmagoria Games LLC,$,NaN,0.00,0,NaN,NaN,"A competitive, fast paced, strategic deck buil...",...,NaN,NaN,0,2.0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"[{'projectTagID': 2, 'isSystem': False, 'isVis...",True,0

In [ ]:
df3