In [11]:
import pandas as pd

df = pd.read_csv("../../02_Data/processed/final_rewards_tags.csv")

In [14]:
df.rename(columns={"단품 여부": "single_item"}, inplace=True)

In [15]:
df

,main_name,projectID,anchorRelativeUrl,price,isDiscounted,effectivePrice,isFeatured,purchasedCopiesCount,backgroundUrl,installmentCost,installmentMinPayment,hasLimitedStock,productCanBePurchased,productID,remainingStockLimit,single_item
0,We Played God - A Survival Miniatures Game,5787,core-rules-physical-pdf-80323,60.0,False,60.0,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,75.0,False,False,80323,NaN,1.0
1,We Played God - A Survival Miniatures Game,5787,eden-visitor-digital-pdfs-digital-survivor-stl...,62.0,False,62.0,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,75.0,False,False,81221,NaN,NaN
2,We Played God - A Survival Miniatures Game,5787,eden-visitor-physical-core-rules-survivor-mini...,124.0,True,110.0,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,75.0,False,False,80326,NaN,NaN
3,We Played God - A Survival Miniatures Game,5787,eden-hacker-digital-all-in-81322,147.0,True,132.0,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,75.0,False,False,81322,NaN,NaN
4,We Played God - A Survival Miniatures Game,5787,eden-visitor-deluxe-physical-core-rules-surviv...,159.0,True,145.0,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,75.0,False,False,81320,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2102,Crossroads Inn: The Board Game,1143,6-x-crossroads-inn-the-board-game-standard-edi...,300.0,True,264.0,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,19155,NaN,NaN
2103,Goldenstar: The Galactic Tournament,1325,champion-gameplay-all-in-18047,72.0,False,72.0,True,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,18047,NaN,NaN
2104,Goldenstar: The Galactic Tournament,1325,goldenstar-core-pledge-17700,43.0,False,43.0,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,17700,NaN,1.0
2105,Goldenstar: The Galactic Tournament,1325,challenger-18042,69.0,False,69.0,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,18042,NaN,NaN
2106,Goldenstar: The Galactic Tournament,1325,legend-all-in-18052,97.0,False,97.0,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,18052,NaN,NaN

In [16]:
df.loc[df['single_item']==1]

,main_name,projectID,anchorRelativeUrl,price,isDiscounted,effectivePrice,isFeatured,purchasedCopiesCount,backgroundUrl,installmentCost,installmentMinPayment,hasLimitedStock,productCanBePurchased,productID,remainingStockLimit,single_item
0,We Played God - A Survival Miniatures Game,5787,core-rules-physical-pdf-80323,60.00,False,60.00,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,75.0,False,False,80323,NaN,1.0
10,CARNIVORE,6481,megapredator-digital-102621,57.00,False,57.00,False,0,https://imgcdn.gamefound.com/productimage/proj...,28.5,100.0,False,False,102621,NaN,1.0
17,1809: Talavera,8024,backers-copy-1809-talavera-99555,69.99,True,56.99,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,99555,NaN,1.0
19,Comber Cat,8225,cat-lovers-99754,20.00,False,20.00,True,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,99754,NaN,1.0
20,Jano - A Pawsome Adventure,5995,jano-board-game-92756,25.00,False,25.00,True,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,92756,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2092,Tectonia,2109,tectonia-the-boardgame-with-all-unlocked-stret...,70.00,False,70.00,True,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,26743,NaN,1.0
2094,Invasion Cards,2149,the-evil-earthworm--26496,19.90,True,13.90,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,26496,NaN,1.0
2096,MOOGH,1919,moogh-the-basic-pledge-24022,36.00,True,23.00,True,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,24022,NaN,1.0
2099,Crossroads Inn: The Board Game,1143,crossroads-inn-the-board-game-standard-edition...,50.00,False,50.00,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,19113,NaN,1.0
2104,Goldenstar: The Galactic Tournament,1325,goldenstar-core-pledge-17700,43.00,False,43.00,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,17700,NaN,1.0

In [17]:
len(set(df.loc[df['single_item']==1]['projectID']))

484

In [18]:
for i in set(df['projectID']):
    if i not in set(df.loc[df['single_item']==1]['projectID']):
        print(i)

In [19]:
df.loc[df['single_item']==1]["projectID"].value_counts()

projectID
5787    1
1103    1
8475    1
6626    1
8150    1
       ..
3119    1
3453    1
3695    1
3844    1
1325    1
Name: count, Length: 484, dtype: int64

In [21]:
df=df.loc[df['single_item']==1]

In [22]:
df.to_csv("../../02_Data/processed/final_rewards_typical.csv", index=False, encoding="utf-8-sig")