In [35]:
import pandas as pd

df = pd.read_csv("../../02_Data/raw/rewards.csv")

In [36]:
pd.set_option('display.max_columns', None)
df.head()

,main_name,projectID_id,raw_url,anchorRelativeUrl,backgroundUrl,deliveryDateRemarks,estimatedDeliveryAt,hasDetails,isExposed,isMostPopular,purchasedCopiesCount,additionalInfoUrl,hasInstallmentsAvailable,installmentCost,installmentMinPayment,abstract,categoryID,effectivePrice,hasLimitedStock,hasRetailerAccess,hasSpecialAccess,imageUrl,isDigital,isDiscounted,isFeatured,name,price,productCanBePurchased,productCanBePurchasedDescription,productID,projectID,remainingStockLimit,url,productState
0,We Played God - A Survival Miniatures Game,5787,https://gamefound.com/api/projectContents/getR...,core-rules-physical-pdf-80323,https://imgcdn.gamefound.com/productimage/proj...,\n,2026-02-01T00:00:00Z,False,False,False,0,NaN,False,NaN,75.0,A copy of the two new books! These books conta...,13888,60.0,False,False,False,https://imgcdn.gamefound.com/productimage/proj...,False,False,False,Core Rules PHYSICAL + PDF,60.0,False,You can't add items to your pledge at this time.,80323,5787,NaN,/en/projects/black-site-studios/we-played-god#...,2
1,We Played God - A Survival Miniatures Game,5787,https://gamefound.com/api/projectContents/getR...,eden-visitor-digital-pdfs-digital-survivor-stl...,https://imgcdn.gamefound.com/productimage/proj...,NaN,2026-01-01T00:00:00Z,False,False,False,0,NaN,False,NaN,75.0,The core WPG items in digital form. If you alr...,13888,62.0,False,False,False,https://imgcdn.gamefound.com/productimage/proj...,False,False,False,E.D.E.N Visitor | DIGITAL (PDFs + DIGITAL SURV...,62.0,False,You can't add items to your pledge at this time.,81221,5787,NaN,/en/projects/black-site-studios/we-played-god#...,2
2,We Played God - A Survival Miniatures Game,5787,https://gamefound.com/api/projectContents/getR...,eden-visitor-physical-core-rules-survivor-mini...,https://imgcdn.gamefound.com/productimage/proj...,NaN,2026-01-01T00:00:00Z,False,False,False,0,NaN,False,NaN,75.0,The core WPG items in physical form. If you al...,13888,110.0,False,False,False,https://imgcdn.gamefound.com/productimage/proj...,False,True,False,E.D.E.N Visitor | PHYSICAL (CORE RULES + SURVI...,124.0,False,You can't add items to your pledge at this time.,80326,5787,NaN,/en/projects/black-site-studios/we-played-god#...,2
3,We Played God - A Survival Miniatures Game,5787,https://gamefound.com/api/projectContents/getR...,eden-hacker-digital-all-in-81322,https://imgcdn.gamefound.com/productimage/proj...,NaN,2026-02-01T00:00:00Z,False,False,False,0,NaN,False,NaN,75.0,Grab all the digital items!,13888,132.0,False,False,False,https://imgcdn.gamefound.com/productimage/proj...,False,True,False,EDEN HACKER | DIGITAL ALL IN,147.0,False,You can't add items to your pledge at this time.,81322,5787,NaN,/en/projects/black-site-studios/we-played-god#...,2
4,We Played God - A Survival Miniatures Game,5787,https://gamefound.com/api/projectContents/getR...,eden-visitor-deluxe-physical-core-rules-surviv...,https://imgcdn.gamefound.com/productimage/proj...,NaN,2026-02-01T00:00:00Z,False,False,False,0,NaN,False,NaN,75.0,The core WPG items in physical form. If you al...,13888,145.0,False,False,False,https://imgcdn.gamefound.com/productimage/proj...,False,True,False,EDEN Visitor | DELUXE PHYSICAL (CORE RULES + S...,159.0,False,You can't add items to your pledge at this time.,81320,5787,NaN,/en/projects/black-site-studios/we-played-god#...,2

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2107 entries, 0 to 2106
Data columns (total 34 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   main_name                         2107 non-null   object
 1   projectID_id                      2107 non-null   int64
 2   raw_url                           2107 non-null   object
 3   anchorRelativeUrl                 2107 non-null   object
 4   backgroundUrl                     2107 non-null   object
 5   deliveryDateRemarks               675 non-null    object
 6   estimatedDeliveryAt               1868 non-null   object
 7   hasDetails                        2107 non-null   bool
 8   isExposed                         2107 non-null   bool
 9   isMostPopular                     2107 non-null   bool
 10  purchasedCopiesCount              2107 non-null   int64
 11  additionalInfoUrl                 0 non-null      float64
 12  hasInstallmentsAvailable          2107 non-null   bool
 13  installmentCost                   368 non-null    float64
 14  installmentMinPayment             1200 non-null   float64
 15  abstract                          1971 non-null   object
 16  categoryID                        2107 non-null   int64
 17  effectivePrice                    2107 non-null   float64
 18  hasLimitedStock                   2107 non-null   bool
 19  hasRetailerAccess                 2107 non-null   bool
 20  hasSpecialAccess                  2107 non-null   bool
 21  imageUrl                          2107 non-null   object
 22  isDigital                         2107 non-null   bool
 23  isDiscounted                      2107 non-null   bool
 24  isFeatured                        2107 non-null   bool
 25  name                              2107 non-null   object
 26  price                             2107 non-null   float64
 27  productCanBePurchased             2107 non-null   bool
 28  productCanBePurchasedDescription  2101 non-null   object
 29  productID                         2107 non-null   int64
 30  projectID                         2107 non-null   int64
 31  remainingStockLimit               476 non-null    float64
 32  url                               2107 non-null   object
 33  productState                      2107 non-null   int64
dtypes: bool(11), float64(6), int64(6), object(11)
memory usage: 401.4+ KB

In [38]:
df.columns

Index(['main_name', 'projectID_id', 'raw_url', 'anchorRelativeUrl',
       'backgroundUrl', 'deliveryDateRemarks', 'estimatedDeliveryAt',
       'hasDetails', 'isExposed', 'isMostPopular', 'purchasedCopiesCount',
       'additionalInfoUrl', 'hasInstallmentsAvailable', 'installmentCost',
       'installmentMinPayment', 'abstract', 'categoryID', 'effectivePrice',
       'hasLimitedStock', 'hasRetailerAccess', 'hasSpecialAccess', 'imageUrl',
       'isDigital', 'isDiscounted', 'isFeatured', 'name', 'price',
       'productCanBePurchased', 'productCanBePurchasedDescription',
       'productID', 'projectID', 'remainingStockLimit', 'url', 'productState'],
      dtype='object')

In [39]:
df['isMostPopular'].value_counts()

False    2107
Name: isMostPopular, dtype: int64

In [40]:
df['isExposed'].value_counts()

False    2107
Name: isExposed, dtype: int64

In [41]:
df['isDigital'].value_counts()

False    2107
Name: isDigital, dtype: int64

In [42]:
df['hasRetailerAccess'].value_counts()

False    2107
Name: hasRetailerAccess, dtype: int64

In [43]:
df['isDigital'].value_counts()

False    2107
Name: isDigital, dtype: int64

In [44]:
df['productCanBePurchasedDescription'].value_counts()

You can't add items to your pledge at this time.                                                            1480
You can't add items to your pledge because this project is closed.                                           427
You can't add items to your pledge because the Pledge Manager for this project hasn't been launched yet.     194
Name: productCanBePurchasedDescription, dtype: int64

In [45]:
df['remainingStockLimit'].value_counts()

0.0      217
1.0       26
100.0     13
2.0       12
5.0       10
        ...
48.0       1
62.0       1
418.0      1
837.0      1
498.0      1
Name: remainingStockLimit, Length: 121, dtype: int64

In [46]:
target_columns = ['main_name', 'projectID_id', 'anchorRelativeUrl', 'name', 'price', 'isDiscounted', 'effectivePrice',
        'isFeatured' , 'estimatedDeliveryAt',  'purchasedCopiesCount', 'abstract', 'categoryID', 
       'hasLimitedStock','productCanBePurchased', 'productCanBePurchasedDescription', 'remainingStockLimit',
       'isMostPopular','isDigital', 'isExposed', 'hasRetailerAccess', 'hasSpecialAccess',]

In [ ]:
b_list = [ 'main_name', 'projectID', 'anchorRelativeUrl', 'price','isDiscounted', 'effectivePrice', 'isFeatured', 'purchasedCopiesCount',
        'installmentCost', 'installmentMinPayment', 'hasLimitedStock', 'productCanBePurchased',
       'productID','remainingStockLimit', 'backgroundUrl']

In [50]:
df = df[b_list]

In [52]:
df

,main_name,projectID,anchorRelativeUrl,price,isDiscounted,effectivePrice,isFeatured,purchasedCopiesCount,backgroundUrl,installmentCost,installmentMinPayment,hasLimitedStock,productCanBePurchased,productID,remainingStockLimit
0,We Played God - A Survival Miniatures Game,5787,core-rules-physical-pdf-80323,60.0,False,60.0,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,75.0,False,False,80323,NaN
1,We Played God - A Survival Miniatures Game,5787,eden-visitor-digital-pdfs-digital-survivor-stl...,62.0,False,62.0,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,75.0,False,False,81221,NaN
2,We Played God - A Survival Miniatures Game,5787,eden-visitor-physical-core-rules-survivor-mini...,124.0,True,110.0,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,75.0,False,False,80326,NaN
3,We Played God - A Survival Miniatures Game,5787,eden-hacker-digital-all-in-81322,147.0,True,132.0,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,75.0,False,False,81322,NaN
4,We Played God - A Survival Miniatures Game,5787,eden-visitor-deluxe-physical-core-rules-surviv...,159.0,True,145.0,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,75.0,False,False,81320,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2102,Crossroads Inn: The Board Game,1143,6-x-crossroads-inn-the-board-game-standard-edi...,300.0,True,264.0,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,19155,NaN
2103,Goldenstar: The Galactic Tournament,1325,champion-gameplay-all-in-18047,72.0,False,72.0,True,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,18047,NaN
2104,Goldenstar: The Galactic Tournament,1325,goldenstar-core-pledge-17700,43.0,False,43.0,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,17700,NaN
2105,Goldenstar: The Galactic Tournament,1325,challenger-18042,69.0,False,69.0,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,18042,NaN
2106,Goldenstar: The Galactic Tournament,1325,legend-all-in-18052,97.0,False,97.0,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,18052,NaN

In [51]:
df.to_csv("../../02_data/processed/final_rewards.csv", index=False, encoding="utf-8-sig")