In [1]:
import pandas as pd

df = pd.read_csv("../02_Data/raw/gamefound_list.csv")

In [3]:
df.columns

Index(['name', 'projectID', 'creator', 'creatorID', 'homeUrl',
       'currencySymbol', 'campaignGoal', 'fundsGathered', 'backersCount',
       'campaignStart', 'campaignEnd', 'description', 'project_url',
       'phaseLabel', 'enableBoardGameProperties', 'minPlayers', 'maxPlayers',
       'minAge', 'playTime', 'playTimeDescription', 'playTimeUnit',
       'pledgeManagerAvailability', 'fundedInSeconds', 'imageUrl',
       'pledgeManagerSoftCloseDeadline', 'projectTags',
       'enableShippingOnlyMode', 'originalType'],
      dtype='object')

In [19]:
a_list = ['name', 'projectID', 'creator', 'creatorID', 'homeUrl',
       'currencySymbol', 'campaignGoal', 'fundsGathered', 'backersCount',
       'campaignStart', 'campaignEnd',
       'phaseLabel', 'enableBoardGameProperties', 'minPlayers', 'maxPlayers',
       'minAge', 'playTime', 'playTimeUnit',
       'fundedInSeconds', 'imageUrl',
       'pledgeManagerSoftCloseDeadline', 'projectTags',
       'originalType']

In [21]:
pd.set_option('display.max_columns', None)
df = df[a_list]

In [ ]:
# 타플랫폼 펀딩 후 서약 관리 전용
df.loc[df['originalType']==0]

,name,projectID,creator,creatorID,homeUrl,currencySymbol,campaignGoal,fundsGathered,backersCount,campaignStart,campaignEnd,description,project_url,phaseLabel,enableBoardGameProperties,minPlayers,maxPlayers,minAge,playTime,playTimeDescription,playTimeUnit,pledgeManagerAvailability,fundedInSeconds,imageUrl,pledgeManagerSoftCloseDeadline,projectTags,enableShippingOnlyMode,originalType
440,Escape From mars,10054,Dark Frontier Games,4262,https://gamefound.com/creators/dfg,£,NaN,41989.04,705,NaN,NaN,Hidden traitor meets sci-fi horror survival in...,https://gamefound.com:443/en/projects/dfg/esca...,Late Pledge - Open for all,True,1.0,4.0,14.0,80.0,NaN,0,NaN,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Horror, Science Fiction, Survival, Dice Game, ...",NaN,0
442,Beat Box Party,10072,Boiling Point Games,8720,https://gamefound.com/creators/boiling-point-g...,$,NaN,8290.00,65,NaN,NaN,"A fast, chaotic party game where players make ...",https://gamefound.com:443/en/projects/boiling-...,Pledge manager - Open for all,True,3.0,10.0,14.0,15.0,NaN,0,0.0,0,https://imgcdn.gamefound.com/projectimage/proj...,2026-08-31T17:00:00Z,Party game,False,0
446,Travel Bug Card Game,11304,DominoTracks,8807,https://gamefound.com/creators/dominotracks,$,NaN,4584.00,21,NaN,NaN,Travel the world to experience new places and ...,https://gamefound.com:443/en/projects/dominotr...,Late Pledge - Open for all,True,2.0,4.0,8.0,15.0,NaN,0,NaN,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Card Game, Adventure, Family",NaN,0
448,The Malice of Light Adventures Pledge Manager,10154,Twin Tale Studios,7366,https://gamefound.com/creators/twin-tale-studios,$,NaN,78301.58,727,NaN,NaN,A cooperative roguelike boss-battler by the Sa...,https://gamefound.com:443/en/projects/twin-tal...,Pledge manager - Open for all,True,1.0,4.0,14.0,90.0,NaN,0,0.0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Card Game, Fantasy, Dice Game, Strategy, Coope...",False,0
455,The Cats of New Orleans,9843,Raybox Games,278,https://gamefound.com/creators/rayboxgames,C$,NaN,201031.73,1069,NaN,NaN,The Cats of New Orleans - A feline adventure s...,https://gamefound.com:443/en/projects/rayboxga...,Pledge manager - Open for all,True,1.0,4.0,14.0,30.0,NaN,0,0.0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Fantasy, Mythology, Digital, Adventure, Paint",False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2281,GKR: Heavy Hitters,13,Weta Workshop,11,https://gamefound.com/creators/weta-workshop,$,NaN,0.00,0,NaN,NaN,"The near-future is here, and Earth’s abandoned...",https://gamefound.com:443/en/projects/weta-wor...,Pledge manager - Closed,False,NaN,NaN,NaN,NaN,NaN,0,2.0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Wargame, Science Fiction, Dice Game, Area Control",True,0
2282,Endure The Stars,12,Grimlord Games,10,https://gamefound.com/creators/grimlord-games,£,NaN,0.00,0,NaN,NaN,An epic 1-6 player Sci-Fi co-op fight for surv...,https://gamefound.com:443/en/projects/grimlord...,Pledge manager - Closed,False,NaN,NaN,NaN,NaN,NaN,0,2.0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Science Fiction, Survival",True,0
2283,Star Scrappers: Cave-In,9,Hexy Studio,7,https://gamefound.com/creators/hexy-studio,$,NaN,0.00,0,NaN,NaN,"Become a galactic entrepreneur, a ruthless min...",https://gamefound.com:443/en/projects/hexy-stu...,Pledge manager - Closed,False,NaN,NaN,NaN,NaN,NaN,0,2.0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Card Game, Science Fiction, Deck Building",True,0
2284,Board&Dice,8,Board&Dice,6,https://gamefound.com/creators/board-and-dice,$,NaN,0.00,0,NaN,NaN,"Board&Dice designs, develops, and publishes fa...",https://gamefound.com:443/en/projects/board-an...,Pledge manager - Closed,False,NaN,NaN,NaN,NaN,NaN,0,2.0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Exploration, Fantasy, Card Game, History, Stra...",True,0
2285,BATTALIA: The Stormgates,3,Fantasmagoria Games LLC,5,https://gamefound.com/creators/fantasmagoria-g...,$,NaN,0.00,0,NaN,NaN,"A competitive, fast paced, strategic deck buil...",https://gamefound.com:443/en/projects/fantasma...,Pledge manager - Closed,False,NaN,NaN,NaN,NaN,NaN,0,2.0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Card Game, Fantasy, Strategy, Terrain Building...",True,0

In [26]:
df.loc[df['originalType']==1]

,name,projectID,creator,creatorID,homeUrl,currencySymbol,campaignGoal,fundsGathered,backersCount,campaignStart,campaignEnd,phaseLabel,enableBoardGameProperties,minPlayers,maxPlayers,minAge,playTime,playTimeUnit,fundedInSeconds,imageUrl,pledgeManagerSoftCloseDeadline,projectTags,originalType
0,Bloodstone,8454,Druid City Games,8843,https://gamefound.com/creators/druid-city-games,$,50000.0,95253.93,479,2026-06-02T13:00:00Z,2026-06-19T22:00:00Z,Crowdfunding,True,1.0,5.0,14.0,60.0,0,7770,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Fantasy, Multiplayer, Competitive, Dice Game, ...",1
2,A Life,9816,Skellig Games,2434,https://gamefound.com/creators/skellig-games,€,10000.0,22796.57,203,2026-06-02T15:00:00Z,2026-06-25T18:00:00Z,Crowdfunding,True,1.0,4.0,8.0,60.0,0,3756,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Set Collection, Competitive, Family, Narrative...",1
3,Growing Season Deluxe Edition,8617,Undigital,5415,https://gamefound.com/creators/undigital,€,8000.0,15291.46,361,2026-06-02T16:00:00Z,2026-06-22T22:00:00Z,Crowdfunding,True,1.0,4.0,8.0,30.0,0,4725,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Card Game, Strategy, Video Game Theme, Multipl...",1
4,Stonesaga Second Printing,9678,Open Owl Studios,474,https://gamefound.com/creators/oomm-games,$,25000.0,154784.30,1791,2026-05-26T15:00:00Z,2026-06-20T00:00:00Z,Crowdfunding,True,1.0,4.0,NaN,90.0,0,1764,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Fantasy, Mythology, Cooperative, Campaign, Civ...",1
5,Beast: Ashfall,8330,Studio Midhall,2936,https://gamefound.com/creators/studio-midhall,€,50000.0,490554.96,3420,2026-05-05T15:00:00Z,2026-06-03T22:00:00Z,Crowdfunding,True,2.0,5.0,14.0,120.0,0,3645,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Fantasy, Strategy, Multiplayer, Competitive, A...",1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2585,Spring and Autumn: Story of China,1446,Mr. B. Games,1954,https://gamefound.com/creators/mr-b-games,$,30000.0,38009.00,219,2021-12-01T15:00:00Z,2022-01-04T22:00:00Z,Crowdfunding - Canceled,True,1.0,5.0,13.0,120.0,0,182152,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Exploration, History, Strategy, Area Control",1
2586,Crossroads Inn: The Board Game,1143,Klabater,1510,https://gamefound.com/creators/klabater,€,20000.0,13420.63,158,2021-10-28T14:00:00Z,2021-11-30T15:00:00Z,Crowdfunding - Unsuccessful,True,2.0,4.0,12.0,120.0,0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Fantasy, Strategy, Terrain Building, Humor",1
2587,PACHAMAMA,1170,SitDown,1514,https://gamefound.com/creators/sitdown,€,25000.0,16048.00,318,2021-10-19T17:00:00Z,2021-11-09T18:00:00Z,Crowdfunding - Canceled,True,1.0,4.0,14.0,60.0,0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Exploration, Logical, Deduction, Terrain Building",1
2588,Taverns & Dragons (Canceled),1314,Lord Raccoon Games,356,https://gamefound.com/creators/thelastbottle,€,20000.0,20954.00,470,2021-10-12T13:00:00Z,2021-11-03T22:00:00Z,Crowdfunding - Canceled,True,2.0,5.0,10.0,60.0,0,433495,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Exploration, Card Game, Fantasy, Dice Game, St...",1
2589,Goldenstar: The Galactic Tournament,1325,Gindi,64,https://gamefound.com/creators/gindi,€,30000.0,10890.00,148,2021-10-05T16:00:00Z,2021-10-29T16:00:00Z,Crowdfunding - Unsuccessful,True,2.0,4.0,14.0,60.0,0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Science Fiction, Area Control, Deck Building",1

In [39]:
df.loc[df['originalType']==1]['phaseLabel'].info()

<class 'pandas.core.series.Series'>
Index: 1402 entries, 0 to 2589
Series name: phaseLabel
Non-Null Count  Dtype
--------------  -----
1402 non-null   object
dtypes: object(1)
memory usage: 21.9+ KB

In [28]:
df.loc[df['originalType']==1]['phaseLabel'].value_counts()

phaseLabel
Upcoming                         389
Pledge manager - Closed          322
Pledge manager - Limited         148
Crowdfunding - Canceled          136
Crowdfunding - Unsuccessful      124
Pledge manager - Open for all    112
Late Pledge - Open for all        89
Crowdfunding - Funded             42
Crowdfunding                      39
Late Pledge - Ended                1
Name: count, dtype: int64

In [41]:
df.loc[df['originalType']==1].info()

<class 'pandas.core.frame.DataFrame'>
Index: 1402 entries, 0 to 2589
Data columns (total 23 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   name                            1402 non-null   object
 1   projectID                       1402 non-null   int64
 2   creator                         1402 non-null   object
 3   creatorID                       1402 non-null   int64
 4   homeUrl                         1402 non-null   object
 5   currencySymbol                  1402 non-null   object
 6   campaignGoal                    1381 non-null   float64
 7   fundsGathered                   1402 non-null   float64
 8   backersCount                    1402 non-null   int64
 9   campaignStart                   1031 non-null   object
 10  campaignEnd                     1181 non-null   object
 11  phaseLabel                      1402 non-null   object
 12  enableBoardGameProperties       1402 non-null   bool
 13  minPlayers                      1360 non-null   float64
 14  maxPlayers                      1360 non-null   float64
 15  minAge                          1311 non-null   float64
 16  playTime                        1327 non-null   float64
 17  playTimeUnit                    1402 non-null   int64
 18  fundedInSeconds                 1402 non-null   int64
 19  imageUrl                        1402 non-null   object
 20  pledgeManagerSoftCloseDeadline  379 non-null    object
 21  projectTags                     1402 non-null   object
 22  originalType                    1402 non-null   int64
dtypes: bool(1), float64(6), int64(6), object(10)
memory usage: 253.3+ KB

In [35]:
df.loc[(df['originalType']==1)&(df['phaseLabel']=="Pledge manager - Limited")]

,name,projectID,creator,creatorID,homeUrl,currencySymbol,campaignGoal,fundsGathered,backersCount,campaignStart,campaignEnd,phaseLabel,enableBoardGameProperties,minPlayers,maxPlayers,minAge,playTime,playTimeUnit,fundedInSeconds,imageUrl,pledgeManagerSoftCloseDeadline,projectTags,originalType
780,Wilderness - A Game of Survival (2nd Edition),6314,FryxGames,7596,https://gamefound.com/creators/fryxgames,€,10000.0,26825.99,341,2025-10-17T13:00:00Z,2025-11-02T11:17:49.67Z,Pledge manager - Limited,True,1.0,8.0,14.0,90.0,0,359528,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Exploration, Survival, Adventure, Multiplayer,...",1
781,PANDORA CELESTE: Pirates & Salvage,6415,Guntower Games,3411,https://gamefound.com/creators/guntower-mike,£,4250.0,13988.05,188,2026-02-24T13:00:00Z,2026-03-11T23:59:00Z,Pledge manager - Limited,True,1.0,9.0,14.0,90.0,0,22620,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-30T22:00:00Z,"Horror, Science Fiction, Survival, Humor, Acti...",1
782,LONG DARK SEA,3879,DELUSIO GAMES,4380,https://gamefound.com/creators/delusio-games,€,60000.0,299955.85,1940,2024-05-01T08:00:00Z,2024-05-21T21:59:00Z,Pledge manager - Limited,True,1.0,4.0,14.0,90.0,0,19645,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Card Game, Fantasy, Strategy, Science Fiction,...",1
783,Colleagues,5539,Creardo,4317,https://gamefound.com/creators/creardo,€,1800.0,8951.46,234,2026-01-28T17:00:00Z,2026-02-25T23:09:00Z,Pledge manager - Limited,True,2.0,5.0,8.0,25.0,0,53277,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Card Game, Survival, Modern, Humor, Party game...",1
784,The Glasgow Train Robbery,6116,SaltandPepper,2354,https://gamefound.com/creators/saltandpepper,€,8000.0,66238.45,1565,2026-03-12T15:00:00Z,2026-04-09T16:29:20.923Z,Pledge manager - Limited,True,2.0,2.0,10.0,30.0,0,4858,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Strategy, History, Cooperative, Asymmetric",1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1624,Master Dater,1742,Cyanide & Happiness,2182,https://gamefound.com/creators/cyanideandhappi...,$,42069.0,640227.00,10468,2022-04-05T15:00:00Z,2022-05-06T02:00:00Z,Pledge manager - Limited,True,3.0,6.0,13.0,20.0,0,3030,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-13T18:00:00Z,"Card Game, Humor, Party game, Competitive, Mul...",1
1637,Wild Realms,1341,Daywalker Syndicate,1658,https://gamefound.com/creators/daywalker-syndi...,$,18000.0,22513.00,255,2021-11-04T16:00:00Z,2021-12-01T02:00:00Z,Pledge manager - Limited,True,2.0,4.0,12.0,60.0,0,1000679,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-09T11:00:00Z,"Card Game, Set Collection",1
1672,Total War: ROME: The Board Game,1346,Colour Command & Combat Ltd,373,https://gamefound.com/creators/psc-games,£,45000.0,532858.00,3702,2022-01-20T18:00:00Z,2022-02-08T21:00:00Z,Pledge manager - Limited,True,1.0,4.0,10.0,180.0,0,2157,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Card Game, History, Wargame, Dice Game, Strate...",1
1731,Masters of the Universe: Fields of Eternia,242,Archon Studio,12,https://gamefound.com/creators/archon-studio,€,50000.0,912028.00,5317,2021-08-10T14:00:00Z,2021-08-24T21:00:00Z,Pledge manager - Limited,True,1.0,6.0,12.0,90.0,0,578,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-13T06:00:00Z,"Adventure, Collectible Models, Cooperative",1
1836,Robinson Crusoe - Collector's Edition,881,Portal Games,136,https://gamefound.com/creators/portalgames,€,50000.0,2277000.00,17313,2021-03-23T17:00:00Z,2021-04-13T16:00:00Z,Pledge manager - Limited,True,1.0,4.0,12.0,90.0,0,1094,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-14T15:00:00Z,"Exploration, Survival, Adventure",1

In [38]:
df.loc[df['originalType']==1]['campaignGoal'].isnull().value_counts()

campaignGoal
False    1381
True       21
Name: count, dtype: int64

rewardss

In [42]:
df2 = pd.read_csv("../02_Data/raw/rewards.csv")

In [43]:
df2

,Unnamed: 0,main_name,projectID_id,raw_url,anchorRelativeUrl,backgroundUrl,deliveryDateRemarks,estimatedDeliveryAt,hasDetails,isExposed,isMostPopular,purchasedCopiesCount,additionalInfoUrl,hasInstallmentsAvailable,installmentCost,installmentMinPayment,abstract,categoryID,effectivePrice,hasLimitedStock,hasRetailerAccess,hasSpecialAccess,imageUrl,isDigital,isDiscounted,isFeatured,name,price,productCanBePurchased,productCanBePurchasedDescription,productID,projectID,remainingStockLimit,url,productState
0,0,Bloodstone,8454,https://gamefound.com/api/projectContents/getR...,gameplay-all-in-deluxe-pledge-107665,https://imgcdn.gamefound.com/productimage/proj...,NaN,2027-05-30T00:00:00Z,False,False,False,456,NaN,True,44.75,25.0,Enter the Arena with the Gameplay All-In Delux...,18887,179.0,False,False,False,https://imgcdn.gamefound.com/productimage/proj...,False,True,True,Gameplay All-In Deluxe Pledge,230.0,True,NaN,107665,8454,NaN,/en/projects/druid-city-games/bloodstone#/prod...,2
1,1,Bloodstone,8454,https://gamefound.com/api/projectContents/getR...,retail-base-edition--108009,https://imgcdn.gamefound.com/productimage/proj...,NaN,2025-06-01T00:00:00Z,False,False,False,9,NaN,True,17.25,25.0,Enter the Arena with the Retail Base Edition o...,18887,69.0,False,False,False,https://imgcdn.gamefound.com/productimage/proj...,False,True,False,Retail Base Edition,75.0,True,NaN,108009,8454,NaN,/en/projects/druid-city-games/bloodstone#/prod...,2
2,2,Bloodstone,8454,https://gamefound.com/api/projectContents/getR...,deluxe-base-edition-107663,https://imgcdn.gamefound.com/productimage/proj...,NaN,2027-05-30T00:00:00Z,False,False,False,7,NaN,True,32.25,25.0,Enter the Arena with the Deluxe Base Edition o...,18887,129.0,False,False,False,https://imgcdn.gamefound.com/productimage/proj...,False,True,False,Deluxe Base Edition,140.0,True,NaN,107663,8454,NaN,/en/projects/druid-city-games/bloodstone#/prod...,2
3,3,Aeolis,8619,https://gamefound.com/api/projectContents/getR...,aeolis-with-metal-coins-english-version--107326,https://imgcdn.gamefound.com/productimage/proj...,NaN,2026-06-09T00:00:00Z,False,False,False,54,NaN,True,19.90,16.9,Aeolis is a fully cooperative kingdom-building...,19268,199.0,True,False,False,https://imgcdn.gamefound.com/productimage/proj...,False,False,True,Aeolis with Metal Coins - English Version 🇬🇧,199.0,True,NaN,107326,8619,6.0,/en/projects/meeple-pug/aeolis#/product/107326,2
4,4,Aeolis,8619,https://gamefound.com/api/projectContents/getR...,aeolis-english-version--107324,https://imgcdn.gamefound.com/productimage/proj...,NaN,2026-06-09T00:00:00Z,False,False,False,5,NaN,True,16.90,16.9,Aeolis is a fully cooperative kingdom-building...,19268,169.0,True,False,False,https://imgcdn.gamefound.com/productimage/proj...,False,False,False,Aeolis - English Version 🇬🇧,169.0,True,NaN,107324,8619,0.0,/en/projects/meeple-pug/aeolis#/product/107324,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11141,11141,Taverns & Dragons (Canceled),1314,https://gamefound.com/api/projectContents/getR...,group-pledge-17696,https://imgcdn.gamefound.com/productimage/proj...,<div>This is an estimated delivery time.</div>,2022-09-01T00:00:00Z,False,False,False,0,NaN,False,NaN,NaN,Buy 5 copies of Taverns & Dragons and get one ...,3054,220.0,False,False,False,https://imgcdn.gamefound.com/productimage/proj...,False,True,False,Group Pledge,264.0,False,You can't add items to your pledge because thi...,17696,1314,NaN,/en/projects/thelastbottle/taverns-and-dragons...,2
11142,11142,Goldenstar: The Galactic Tournament,1325,https://gamefound.com/api/projectContents/getR...,champion-gameplay-all-in-18047,https://imgcdn.gamefound.com/productimage/proj...,NaN,2022-06-01T00:00:00Z,False,False,False,0,NaN,False,NaN,NaN,"This pledge includes Goldenstar Core Box, Crow...",3066,72.0,False,False,False,https://imgcdn.gamefound.com/productimage/proj...,False,False,True,Champion (Gameplay All-in),72.0,False,You can't add items to your pledge because thi...,18047,1325,NaN,/en/projects/gindi/goldenstar-the-galactic-tou...,2
11143,11143,Goldenstar: The Galactic Tournament,1325,https://gamefound.com/api/projectContents/getR...,goldenstar-core-pledge-17700,https://imgcdn.gamefound.com/productimage/proj...,NaN,2022-06-01T00:00:00Z,False,False,False,0,NaN,False,NaN,NaN,"This pledge includes Goldenstar Core Box, incl...",3066,43.0,False,False,False,https://imgcdn.gamefound.com/productimage/proj...,False,False,False,Goldenstar Core Pledge,43.0,False,You can't add items to your pledge because thi...,17700,1325,NaN,/en/projects/gindi/goldenstar-the-galactic-tou...,2
11144,11144,Goldenstar: The Galactic Tournament,1325,https://gamefound.com/api/projectContents/getR...,challenger-18042,https://imgcdn.gamefound.com/productimage/proj...,NaN,2022-06-01T00:00:00Z,False,False,False,0,NaN,False,NaN,NaN,"This pledge includes Goldenstar Core Box, Crow...",3066,69.0,False,False,False,https://imgcdn.gamefound.com/productimage/proj...,False,False,False,Challenger,69.0,False,You can't add items to your pledge because thi...,18042,1325,NaN,/en/projects/gindi/goldenstar-the-galactic-tou...,2
11145,11145,Goldenstar: The Galactic Tournament,1325,https://gamefound.com/api/projectContents/getR...,legend-all-in-18052,https://imgcdn.gamefound.com/productimage/proj...,NaN,2022-06-01T00:00:00Z,False,False,False,0,NaN,False,NaN,NaN,"This pledge includes Goldenstar Core Box, Crow...",3066,97.0,False,False,False,https://imgcdn.gamefound.com/productimage/proj...,False,False,False,Legend (All-in),97.0,False,You can't add items to your pledge because thi...,18052,1325,NaN,/en/projects/gindi/goldenstar-the-galactic-tou...,2

In [45]:
df2.columns

Index(['Unnamed: 0', 'main_name', 'projectID_id', 'raw_url',
       'anchorRelativeUrl', 'backgroundUrl', 'deliveryDateRemarks',
       'estimatedDeliveryAt', 'hasDetails', 'isExposed', 'isMostPopular',
       'purchasedCopiesCount', 'additionalInfoUrl', 'hasInstallmentsAvailable',
       'installmentCost', 'installmentMinPayment', 'abstract', 'categoryID',
       'effectivePrice', 'hasLimitedStock', 'hasRetailerAccess',
       'hasSpecialAccess', 'imageUrl', 'isDigital', 'isDiscounted',
       'isFeatured', 'name', 'price', 'productCanBePurchased',
       'productCanBePurchasedDescription', 'productID', 'projectID',
       'remainingStockLimit', 'url', 'productState'],
      dtype='object')

In [ ]:
b_list = [ 'main_name', 'projectID',
       'anchorRelativeUrl', 'backgroundUrl',
       'purchasedCopiesCount',
       'installmentCost', 'installmentMinPayment',
        'hasLimitedStock',
       'isDiscounted', 'price', 'effectivePrice',
       'isFeatured',   'productCanBePurchased',
       'productID',
       'remainingStockLimit']

In [46]:
df2["hasDetails"]==tru

0        False
1        False
2        False
3        False
4        False
         ...
11141    False
11142    False
11143    False
11144    False
11145    False
Name: hasDetails, Length: 11146, dtype: bool

comment

In [47]:
df3 = pd.read_csv("../02_Data/raw/gamefound_ALL_comments_Hierarchical.csv")

In [48]:
df3

,project_name,comment_id,parent_id,depth_level,author_id,author_name,creator_id,is_pledge_master,is_backer,backer_number,is_prior_backer,is_pathfinder,has_children,children_count,text,created_at,likes
0,Stonesaga Second Printing,2598484,NaN,0,244541,BrendanMcCaskell,1,False,False,NaN,False,False,False,0,Funded! Let's keep it going!,2026-05-26T15:30:56.06Z,11
1,Stonesaga Second Printing,2611664,NaN,0,1378081,Mathias_VN,0,False,False,NaN,False,False,True,1,Since I didn’t own the previous version of Sto...,2026-06-01T18:14:19.01Z,0
2,Stonesaga Second Printing,2611763,2611664.0,1,1359539,mightygoat,0,False,True,779.0,True,False,False,0,You wouldn't need the ERRATA pack. The rechar...,2026-06-01T19:11:00.073Z,0
3,Stonesaga Second Printing,2611527,NaN,0,1913147,Clavagan,0,False,False,NaN,False,False,False,0,Esiste anche con traduzione italiana?,2026-06-01T16:55:25.363Z,0
4,Stonesaga Second Printing,2609072,NaN,0,515392,Remo,0,True,True,606.0,True,False,True,6,Shouldnt Errata pack include a free journal bo...,2026-05-31T04:51:54.227Z,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1585624,Goldenstar: The Galactic Tournament,115587,115520.0,1,64315,Darken,1,False,False,NaN,False,False,False,0,"You start with cards from both Characters, but...",2021-09-21T19:19:50.52Z,0
1585625,Goldenstar: The Galactic Tournament,115489,NaN,0,246326,Basti,0,True,False,NaN,False,False,True,1,Is there a possibility for a german version of...,2021-09-21T17:42:03.717Z,1
1585626,Goldenstar: The Galactic Tournament,118641,115489.0,1,178062,Piotr_Gindi,0,False,False,NaN,False,False,False,0,Unfortunately not at the moment :/,2021-09-28T08:59:12.633Z,0
1585627,Goldenstar: The Galactic Tournament,115326,NaN,0,130137,BigBenMagnus,0,False,False,NaN,False,False,True,1,Do you plan to make a miniature only pledge ?,2021-09-21T13:28:30.39Z,0
1585628,Goldenstar: The Galactic Tournament,115344,115326.0,1,64315,Darken,1,False,False,NaN,False,False,False,0,"Unfortunately no, but if there will be a massi...",2021-09-21T14:10:21.233Z,0

In [50]:
df3.columns

Index(['project_name', 'comment_id', 'parent_id', 'depth_level', 'author_id',
       'author_name', 'creator_id', 'is_pledge_master', 'is_backer',
       'backer_number', 'is_prior_backer', 'is_pathfinder', 'has_children',
       'children_count', 'text', 'created_at', 'likes'],
      dtype='object')

In [ ]:
c_list = ['project_name', 'comment_id', 'parent_id', 'depth_level', 'author_id',
       'author_name', 'creator_id', 'is_pledge_master', 'is_backer',
       'is_prior_backer', 'is_pathfinder', 'has_children',
       'children_count', 'text', 'created_at', 'likes']