In [ ]:
import requests
import pandas as pd

api_url = "https://gamefound.com/api/projectSearch/searchProjectsForCards"

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
}

payload = {
    "creatorID": None,
    "creatorName": None,
    "sortType": 0,
    "term": "",
    "projectPhaseSearchTypes": [],
    "projectBenefits": [],
    "projectTags": [],
    "projectCatalogCategories": [11], #보드게임 카테고리 11번
    "playerAges": [],
    "playerCounts": [],
    "playTimes": [],
    "creator": {"creatorID": None, "name": None},
    "userCommunitySearchTypes": [],
    "source": 5,
    "pageIndex": 0 # 0페이지부터 시작 -> 이거 돌려야함
}

response = requests.post(api_url, headers=headers, json=payload)

# 응답 확인
if response.status_code == 200:
    data = response.json()
    print("성공")

else:
    print(f"실패 : {response.status_code}")

성공

In [32]:
temp  = data['projects']['pagedItems'][0]
temp

{'allowNewOrders': None,
 'campaignGoal': 25000,
 'coCreators': [],
 'creator': {'avatarUrl': 'https://imgcdn.gamefound.com/creatoricon/creators/474/704e7ea9-95bc-4ecc-9f72-e38484f4eccd.png',
  'homeUrl': 'https://gamefound.com/creators/oomm-games',
  'creatorID': 474,
  'imageFileName': '704e7ea9-95bc-4ecc-9f72-e38484f4eccd.png',
  'name': 'Open Owl Studios',
  'urlName': 'oomm-games'},
 'draftAccessKey': 'AS5GA0LMT7OGJC3IIUNV8DGE3BX',
 'enableShippingOnlyMode': None,
 'hasPromoItem': False,
 'lastUpdateTitle': None,
 'phaseLabel': 'Crowdfunding',
 'pledgeManagerAvailability': None,
 'pledgeManagerSoftCloseDeadline': None,
 'projectProperties': {'enableBoardGameProperties': True,
  'maxPlayers': 4,
  'minAge': None,
  'minPlayers': 1,
  'playTime': 90,
  'playTimeDescription': None,
  'playTimeUnit': 0},
 'projectUrlName': 'stonesaga-second-printing',
 'promoItemName': None,
 'useDraftAccessKey': False,
 'backersCount': 1658,
 'campaignEnd': '2026-06-20T00:00:00Z',
 'campaignStart': '2026-05-26T15:00:00Z',
 'campaignEndScheduledAt': '2026-06-20T00:00:00Z',
 'campaignOutcome': 0,
 'catalogCategory': {'projectCategory': 11,
  'name': 'Board & card games',
  'url': '/en/projects/search?projectCatalogCategories=BoardAndCardGames'},
 'currencySymbol': '$',
 'followerCount': 8843,
 'fundedInSeconds': 1764,
 'fundsGathered': 142095.28,
 'fundsGatheredPresentation': 0,
 'imageUrl': 'https://imgcdn.gamefound.com/projectimage/projects/9678/0e9a20f1-7e79-4057-9f51-2d957a571d56.png',
 'installmentCount': 4,
 'installmentMinPayment': 100.0,
 'name': 'Stonesaga Second Printing',
 'originalType': 1,
 'phase': 10,
 'phaseEndedAt': '2026-06-20T00:00:00Z',
 'phaseStartedAt': '2026-05-26T15:00:00Z',
 'platform': 0,
 'projectBadges': [0, 1],
 'projectID': 9678,
 'projectLabels': [],
 'projectTags': [{'projectTagID': 1,
   'isSystem': False,
   'isVisible': True,
   'name': 'Fantasy',
   'url': '/en/projects/search?projectTags=1',
   'urlName': 'fantasy'},
  {'projectTagID': 7,
   'isSystem': False,
   'isVisible': True,
   'name': 'Mythology',
   'url': '/en/projects/search?projectTags=7',
   'urlName': 'mythology'},
  {'projectTagID': 34,
   'isSystem': False,
   'isVisible': True,
   'name': 'Cooperative',
   'url': '/en/projects/search?projectTags=34',
   'urlName': 'cooperative'},
  {'projectTagID': 40,
   'isSystem': False,
   'isVisible': True,
   'name': 'Campaign',
   'url': '/en/projects/search?projectTags=40',
   'urlName': 'campaign'},
  {'projectTagID': 41,
   'isSystem': False,
   'isVisible': True,
   'name': 'Civilization',
   'url': '/en/projects/search?projectTags=41',
   'urlName': 'civilization'}],
 'shortDescription': 'Build a civilization across epochs in a cooperative survival crafting saga set in a persistent world shaped by your choices.',
 'type': 1,
 'url': 'https://gamefound.com:443/en/projects/oomm-games/stonesaga-second-printing',
 'relativeUrl': '/en/projects/oomm-games/stonesaga-second-printing',
 'version': 1,
 'visibility': 0}

In [ ]:
projects = data.get('projects', {}).get('pagedItems', [])
game_list = []
    
for item in projects:
    game_dict = {
        'name': item.get('name'),                       # 프로젝트명
        'creator': item.get('creator').get('name'),     # 크리에이터 이름
        'currencySymbol': item.get('currencySymbol'),   # 화폐단위  ->  여러개임.....;;
        'campaignGoal': item.get('campaignGoal'),       # 목표 금액
        'fundsGathered': item.get('fundsGathered'),     # 모금액
        'backersCount': item.get('backersCount'),       # 후원자 수
        'campaignStart': item.get('campaignStart'),     # 시작일
        'campaignEnd': item.get('campaignEnd'),         # 마감일
        'description': item.get('shortDescription'),    # 설명
        'project_url': item.get('url'),                  # 프로젝트 링크 -> 이거로 추가 크롤링 해야함
        
        'enableBoardGameProperties': item.get('projectProperties').get('enableBoardGameProperties'), # ?
        'minPlayers': item.get('projectProperties').get('minPlayers'), # 최소인원
        'maxPlayers': item.get('projectProperties').get('maxPlayers'), # 최대인원
        'minAge': item.get('projectProperties').get('minAge'), # 연령제한
        'playTime': item.get('projectProperties').get('playTime'), # 플레이타임
        'playTimeDescription': item.get('projectProperties').get('playTimeDescription'), # 설명? 다 비어 있는거 같은데
        'playTimeUnit': item.get('projectProperties').get('playTimeUnit') # ?
    
    
    }
    game_list.append(game_dict)
    
df = pd.DataFrame(game_list)

In [31]:
df

,name,creator,currencySymbol,campaignGoal,fundsGathered,backersCount,campaignEnd,description,project_url,enableBoardGameProperties,minPlayers,maxPlayers,minAge,playTime,playTimeDescription,playTimeUnit
0,Stonesaga Second Printing,Open Owl Studios,$,25000,142095.28,1658,2026-06-20T00:00:00Z,Build a civilization across epochs in a cooper...,https://gamefound.com:443/en/projects/oomm-gam...,True,1,4,NaN,90,None,0
1,Beast: Ashfall,Studio Midhall,€,50000,376075.99,2496,2026-06-03T22:00:00Z,Skies of smoke. Lands of ash. Welcome back to ...,https://gamefound.com:443/en/projects/studio-m...,True,2,5,14.0,120,None,0
2,Capitals of Tactoria,ArcaneArchitect,€,17700,46505.70,463,2026-06-29T22:00:00Z,"Build kingdoms, battle friends, and enjoy fast...",https://gamefound.com:443/en/projects/capitals...,True,1,4,14.0,50,None,0
3,Fall Dawn,Dustiny Games,€,20000,63651.88,737,2026-06-16T17:00:00Z,Fall Dawn is a competitive dungeon-crawler car...,https://gamefound.com:443/en/projects/dustiny-...,True,1,4,14.0,60,None,0
4,VANEA: Guardians of the Eldertree (Relaunch),Forgotten Tales,€,59000,92689.70,534,2026-06-01T16:00:00Z,Welcome to VANEA. A mystical and fairytale - t...,https://gamefound.com:443/en/projects/forgotte...,True,1,4,10.0,90,None,0
5,Pasteles & Conservas: Exotic Tides,SaltandPepper,€,8500,93136.60,1933,2026-06-02T14:00:00Z,Pasteles is a standalone solo game (20–30 minu...,https://gamefound.com:443/en/projects/saltandp...,True,1,1,10.0,30,None,0
6,TATANKA,Creardo,€,5000,15626.11,181,2026-06-25T21:59:00Z,The wind sweeps across the Great Plains. \nThe...,https://gamefound.com:443/en/projects/creardo/...,True,1,4,12.0,80,None,0
7,"Possess Me, Satan",Falling Whale Games,$,10000,38233.40,638,2026-06-20T03:00:00Z,The chaotically fun social deduction game wher...,https://gamefound.com:443/en/projects/dukes-of...,True,5,16,16.0,30,None,0
8,Flockers,Odd Bird,$,25000,74847.88,698,2026-06-05T22:00:00Z,Fly your flock of snow geese southward in this...,https://gamefound.com:443/en/projects/odd-bird...,True,1,4,14.0,45,None,0
9,SYNCANITE FOUNDATION: Reprint + CRIMSON PROTOC...,SYNCANITE GAMES GmbH,€,20000,64346.19,414,2026-05-31T21:59:00Z,Discover SYNCANITE FOUNDATION as a new player ...,https://gamefound.com:443/en/projects/syncanit...,True,1,6,14.0,150,None,0
10,The 30s,Darkkena,€,4800,13637.93,281,2026-06-26T22:00:00Z,The 30s is a descent into horror within an old...,https://gamefound.com:443/en/projects/darkkena...,True,1,2,10.0,15,None,0
11,Ludicurrus,Iconiq Studios,£,10000,23108.65,266,2026-06-10T17:00:00Z,"Ludicurrus is a vibrant, fast-paced chariot ra...",https://gamefound.com:443/en/projects/iconiq-s...,True,1,4,8.0,40,None,0
12,Weasel Wars,dartfrog games,€,18000,39219.72,309,2026-06-08T22:00:00Z,Command ruthless weasel heroes in a living for...,https://gamefound.com:443/en/projects/dartfrog...,True,1,4,10.0,50,None,0
13,Button Shy Spring Collection - International,Button Shy Games,$,2000,7986.29,202,2026-06-06T14:30:00Z,"Choose from Astro ROVE, Jarl, Everything Machi...",https://gamefound.com:443/en/projects/button-s...,True,1,6,14.0,15,None,0
14,Orbital,Firmwar,€,40000,6908.60,26,2026-06-25T16:00:00Z,A cooperative electronic board game where astr...,https://gamefound.com:443/en/projects/firmwar/...,True,1,4,14.0,60,None,0
15,Jure Grando: The first Vampire,InterHuman games,€,4000,17622.80,181,2026-06-05T20:09:00Z,A Folk-Horror Cooperative board game of quiet ...,https://gamefound.com:443/en/projects/interhum...,True,1,4,14.0,60,None,0
16,Hideouts: Legends of The Forest,Weasel & Wolf,£,5000,2011.91,43,2026-06-28T16:00:00Z,"Hideouts is a tile drafting, strategy game for...",https://gamefound.com:443/en/projects/weasel--...,True,2,4,14.0,30,None,0
17,Race to Mars: Lunar Edition,Fur Balloon Games,€,15000,17086.00,469,2026-05-31T21:00:00Z,Race to put the first human being on Mars in t...,https://gamefound.com:443/en/projects/fur-ball...,True,1,4,14.0,75,None,0
18,Dwarf Emberforge,Mythic Ember,€,2450,6080.25,163,2026-06-10T19:00:00Z,Dwarf Emberforge is a fast 2–4-player card-pow...,https://gamefound.com:443/en/projects/mythicem...,True,2,4,12.0,40,None,0
19,Vermines - Deck Building Game,ctrlZEBRE,€,5000,1452.57,25,2026-07-19T21:59:00Z,Vermines is a 2-4 players deckbuilding game wh...,https://gamefound.com:443/en/projects/ctrlzebr...,True,2,4,10.0,40,None,0
20,Kangouroute,Pretexte_editions,€,28000,3631.20,52,2026-06-28T21:59:00Z,"Dans Kangouroute, les animaux de la forêt vois...",https://gamefound.com:443/en/projects/brandonp...,True,2,6,10.0,30,None,0
21,Fluffypede,ShyFinnGames,€,3000,4606.82,70,2026-06-09T15:00:00Z,"Build Fluffypedes together: the longer, the be...",https://gamefound.com:443/en/projects/shy-finn...,True,2,5,8.0,25,None,0
22,Iron Quest: The First Ember [Print & Play],Giza Games,A$,1000,4286.85,145,2026-06-09T12:00:00Z,A Viking sea adventure roll-and-write for 1–4 ...,https://gamefound.com:443/en/projects/giza-gam...,True,1,4,14.0,30,None,0
23,VENATOR: Heroes of the Arena,Red Kingdom Games,€,1000,4156.90,116,2026-06-17T15:00:00Z,"A strategic board game with deckbuilding, focu...",https://gamefound.com:443/en/projects/red-king...,True,2,4,14.0,60,None,0

In [25]:
temp.get('projectProperties')

{'enableBoardGameProperties': True,
 'maxPlayers': 4,
 'minAge': None,
 'minPlayers': 1,
 'playTime': 90,
 'playTimeDescription': None,
 'playTimeUnit': 0}

In [ ]:
import requests
import pandas as pd

api_url = "https://gamefound.com/api/projectSearch/searchProjectsForCards"

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
}

payload = {
    "creatorID": None,
    "creatorName": None,
    "sortType": 0,
    "term": "",
    "projectPhaseSearchTypes": [],
    "projectBenefits": [],
    "projectTags": [],
    "projectCatalogCategories": [11], #보드게임 카테고리 11번
    "playerAges": [],
    "playerCounts": [],
    "playTimes": [],
    "creator": {"creatorID": None, "name": None},
    "userCommunitySearchTypes": [],
    "source": 5,
    "pageIndex": 0 # 0페이지부터 시작 -> 이거 돌려야함
}

response = requests.post(api_url, headers=headers, json=payload)

# 응답 확인
if response.status_code == 200:
    data = response.json()
    print("성공")

else:
    print(f"실패 : {response.status_code}")

In [34]:
data['projects']['totalPageCount']

108

In [50]:
import requests
import pandas as pd
import time

api_url = "https://gamefound.com/api/projectSearch/searchProjectsForCards"

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
}

payload = {
    "creatorID": None,
    "creatorName": None,
    "sortType": 0,
    "term": "",
    "projectPhaseSearchTypes": [],
    "projectBenefits": [],
    "projectTags": [],
    "projectCatalogCategories": [11], #보드게임 카테고리 11번
    "playerAges": [],
    "playerCounts": [],
    "playTimes": [],
    "creator": {"creatorID": None, "name": None},
    "userCommunitySearchTypes": [],
    "source": 5,
    "pageIndex": 0 # 0페이지부터 시작 -> 이거 돌려야함
}

response = requests.post(api_url, headers=headers, json=payload)

# 응답, 전체 페이지 확인
if response.status_code == 200:
    data = response.json()
    total_page =data.get('projects').get('totalPageCount')
    print(f"전체 페이지 : {total_page}")
    print("성공")

else:
    print(f"실패 : {response.status_code}")

print("----------------------------------------------")
# 전체페이지 for문 ㄱㄱ / 총 108페이지

game_list = []

for page in range(total_page):
    print(f"{page} 페이지 시작")

    payload['pageIndex'] = page

    res = requests.post(api_url, headers=headers, json=payload)

    if res.status_code == 200:
        page_data = res.json()
        projects = page_data.get('projects').get('pagedItems')
        
        projects_data = page_data.get('projects')
        first_num = projects_data.get('firstItemNumber')
        last_num = projects_data.get('lastItemNumber')
        print(f"{first_num}~{last_num}개 진행중")
 
        for item in projects:
            game_dict = {
                'name': item.get('name'),                       # 프로젝트명
                'creator': item.get('creator').get('name'),     # 크리에이터 이름
                'currencySymbol': item.get('currencySymbol'),   # 화폐단위  ->  여러개임.....;;
                'campaignGoal': item.get('campaignGoal'),       # 목표 금액
                'fundsGathered': item.get('fundsGathered'),     # 모금액
                'backersCount': item.get('backersCount'),       # 후원자 수
                'campaignStart': item.get('campaignStart'),     # 시작일
                'campaignEnd': item.get('campaignEnd'),         # 마감일
                'description': item.get('shortDescription'),    # 설명
                'project_url': item.get('url'),                  # 프로젝트 링크 -> 이거로 추가 크롤링 해야함
                
                'enableBoardGameProperties': item.get('projectProperties').get('enableBoardGameProperties'), # ?
                'minPlayers': item.get('projectProperties').get('minPlayers'), # 최소인원
                'maxPlayers': item.get('projectProperties').get('maxPlayers'), # 최대인원
                'minAge': item.get('projectProperties').get('minAge'), # 연령제한
                'playTime': item.get('projectProperties').get('playTime'), # 플레이타임
                'playTimeDescription': item.get('projectProperties').get('playTimeDescription'), # 설명? 다 비어 있는거 같은데
                'playTimeUnit': item.get('projectProperties').get('playTimeUnit') # ?
                        
            }
            game_list.append(game_dict)

    else:
        print(f"{page}페이지 실패")
        pass
    
    time.sleep(1.5)

df = pd.DataFrame(game_list)

전체 페이지 : 108
성공
----------------------------------------------
0 페이지 시작
1~24개 진행중
1 페이지 시작
25~48개 진행중
2 페이지 시작
49~72개 진행중
3 페이지 시작
73~96개 진행중
4 페이지 시작
97~120개 진행중
5 페이지 시작
121~144개 진행중
6 페이지 시작
145~168개 진행중
7 페이지 시작
169~192개 진행중
8 페이지 시작
193~216개 진행중
9 페이지 시작
217~240개 진행중
10 페이지 시작
241~264개 진행중
11 페이지 시작
265~288개 진행중
12 페이지 시작
289~312개 진행중
13 페이지 시작
313~336개 진행중
14 페이지 시작
337~360개 진행중
15 페이지 시작
361~384개 진행중
16 페이지 시작
385~408개 진행중
17 페이지 시작
409~432개 진행중
18 페이지 시작
433~456개 진행중
19 페이지 시작
457~480개 진행중
20 페이지 시작
481~504개 진행중
21 페이지 시작
505~528개 진행중
22 페이지 시작
529~552개 진행중
23 페이지 시작
553~576개 진행중
24 페이지 시작
577~600개 진행중
25 페이지 시작
601~624개 진행중
26 페이지 시작
625~648개 진행중
27 페이지 시작
649~672개 진행중
28 페이지 시작
673~696개 진행중
29 페이지 시작
697~720개 진행중
30 페이지 시작
721~744개 진행중
31 페이지 시작
745~768개 진행중
32 페이지 시작
769~792개 진행중
33 페이지 시작
793~816개 진행중
34 페이지 시작
817~840개 진행중
35 페이지 시작
841~864개 진행중
36 페이지 시작
865~888개 진행중
37 페이지 시작
889~912개 진행중
38 페이지 시작
913~936개 진행중
39 페이지 시작
937~960개 진행중
40 페이지 시작
961~984개 진행중
41 페이지 시작
985~1008개 진행중
42 페이지 시작
1009~1032개 진행중
43 페이지 시작
1033~1056개 진행중
44 페이지 시작
1057~1080개 진행중
45 페이지 시작
1081~1104개 진행중
46 페이지 시작
1105~1128개 진행중
47 페이지 시작
1129~1152개 진행중
48 페이지 시작
1153~1176개 진행중
49 페이지 시작
1177~1200개 진행중
50 페이지 시작
1201~1224개 진행중
51 페이지 시작
1225~1248개 진행중
52 페이지 시작
1249~1272개 진행중
53 페이지 시작
1273~1296개 진행중
54 페이지 시작
1297~1320개 진행중
55 페이지 시작
1321~1344개 진행중
56 페이지 시작
1345~1368개 진행중
57 페이지 시작
1369~1392개 진행중
58 페이지 시작
1393~1416개 진행중
59 페이지 시작
1417~1440개 진행중
60 페이지 시작
1441~1464개 진행중
61 페이지 시작
1465~1488개 진행중
62 페이지 시작
1489~1512개 진행중
63 페이지 시작
1513~1536개 진행중
64 페이지 시작
1537~1560개 진행중
65 페이지 시작
1561~1584개 진행중
66 페이지 시작
1585~1608개 진행중
67 페이지 시작
1609~1632개 진행중
68 페이지 시작
1633~1656개 진행중
69 페이지 시작
1657~1680개 진행중
70 페이지 시작
1681~1704개 진행중
71 페이지 시작
1705~1728개 진행중
72 페이지 시작
1729~1752개 진행중
73 페이지 시작
1753~1776개 진행중
74 페이지 시작
1777~1800개 진행중
75 페이지 시작
1801~1824개 진행중
76 페이지 시작
1825~1848개 진행중
77 페이지 시작
1849~1872개 진행중
78 페이지 시작
1873~1896개 진행중
79 페이지 시작
1897~1920개 진행중
80 페이지 시작
1921~1944개 진행중
81 페이지 시작
1945~1968개 진행중
82 페이지 시작
1969~1992개 진행중
83 페이지 시작
1993~2016개 진행중
84 페이지 시작
2017~2040개 진행중
85 페이지 시작
2041~2064개 진행중
86 페이지 시작
2065~2088개 진행중
87 페이지 시작
2089~2112개 진행중
88 페이지 시작
2113~2136개 진행중
89 페이지 시작
2137~2160개 진행중
90 페이지 시작
2161~2184개 진행중
91 페이지 시작
2185~2208개 진행중
92 페이지 시작
2209~2232개 진행중
93 페이지 시작
2233~2256개 진행중
94 페이지 시작
2257~2280개 진행중
95 페이지 시작
2281~2304개 진행중
96 페이지 시작
2305~2328개 진행중
97 페이지 시작
2329~2352개 진행중
98 페이지 시작
2353~2376개 진행중
99 페이지 시작
2377~2400개 진행중
100 페이지 시작
2401~2424개 진행중
101 페이지 시작
2425~2448개 진행중
102 페이지 시작
2449~2472개 진행중
103 페이지 시작
2473~2496개 진행중
104 페이지 시작
2497~2520개 진행중
105 페이지 시작
2521~2544개 진행중
106 페이지 시작
2545~2568개 진행중
107 페이지 시작
2569~2583개 진행중

In [72]:
df.head()

,name,creator,currencySymbol,campaignGoal,fundsGathered,backersCount,campaignStart,campaignEnd,description,project_url,enableBoardGameProperties,minPlayers,maxPlayers,minAge,playTime,playTimeDescription,playTimeUnit
0,Stonesaga Second Printing,Open Owl Studios,$,25000.0,142350.46,1661,2026-05-26T15:00:00Z,2026-06-20T00:00:00Z,Build a civilization across epochs in a cooper...,https://gamefound.com:443/en/projects/oomm-gam...,True,1.0,4.0,NaN,90.0,None,0
1,Beast: Ashfall,Studio Midhall,€,50000.0,377387.22,2502,2026-05-05T15:00:00Z,2026-06-03T22:00:00Z,Skies of smoke. Lands of ash. Welcome back to ...,https://gamefound.com:443/en/projects/studio-m...,True,2.0,5.0,14.0,120.0,None,0
2,Capitals of Tactoria,ArcaneArchitect,€,17700.0,46591.05,463,2026-05-26T15:00:00Z,2026-06-29T22:00:00Z,"Build kingdoms, battle friends, and enjoy fast...",https://gamefound.com:443/en/projects/capitals...,True,1.0,4.0,14.0,50.0,None,0
3,Fall Dawn,Dustiny Games,€,20000.0,63783.77,738,2026-05-19T14:00:00Z,2026-06-16T17:00:00Z,Fall Dawn is a competitive dungeon-crawler car...,https://gamefound.com:443/en/projects/dustiny-...,True,1.0,4.0,14.0,60.0,None,0
4,VANEA: Guardians of the Eldertree (Relaunch),Forgotten Tales,€,59000.0,92825.20,535,2026-05-12T16:00:00Z,2026-06-01T16:00:00Z,Welcome to VANEA. A mystical and fairytale - t...,https://gamefound.com:443/en/projects/forgotte...,True,1.0,4.0,10.0,90.0,None,0

In [52]:
df.tail()

,name,creator,currencySymbol,campaignGoal,fundsGathered,backersCount,campaignStart,campaignEnd,description,project_url,enableBoardGameProperties,minPlayers,maxPlayers,minAge,playTime,playTimeDescription,playTimeUnit
2578,Spring and Autumn: Story of China,Mr. B. Games,$,30000.0,38009.00,219,2021-12-01T15:00:00Z,2022-01-04T22:00:00Z,Welcome to Spring and Autumn: Story of China! ...,https://gamefound.com:443/en/projects/mr-b-gam...,True,1.0,5.0,13.0,120.0,None,0
2579,Crossroads Inn: The Board Game,Klabater,€,20000.0,13420.63,158,2021-10-28T14:00:00Z,2021-11-30T15:00:00Z,Folks! We keep playing games about dungeons an...,https://gamefound.com:443/en/projects/klabater...,True,2.0,4.0,12.0,120.0,None,0
2580,PACHAMAMA,SitDown,€,25000.0,16048.00,318,2021-10-19T17:00:00Z,2021-11-09T18:00:00Z,The Earth Goddess Pachamama constantly guides ...,https://gamefound.com:443/en/projects/sitdown/...,True,1.0,4.0,14.0,60.0,None,0
2581,Taverns & Dragons (Canceled),Lord Raccoon Games,€,20000.0,20954.00,470,2021-10-12T13:00:00Z,2021-11-03T22:00:00Z,Gather magic mushrooms and dragon eggs in the ...,https://gamefound.com:443/en/projects/thelastb...,True,2.0,5.0,10.0,60.0,None,0
2582,Goldenstar: The Galactic Tournament,Gindi,€,30000.0,10890.00,148,2021-10-05T16:00:00Z,2021-10-29T16:00:00Z,"Enter the Tournament in this Asymmetric, Deck ...",https://gamefound.com:443/en/projects/gindi/go...,True,2.0,4.0,14.0,60.0,None,0

In [74]:
import os
current_dir = os.getcwd()
parent_dir = os.path.dirname(current_dir)

df.to_csv(parent_dir+"\\02_Data\\raw\\gamepound_list.csv", index=True, encoding="utf-8-sig")