In [9]:
import pandas as pd
pd.set_option("display.max_columns",None)

df1 = pd.read_csv("../02_Data/processed/final_gamefound_list.csv")
df2 = pd.read_csv("../02_Data/processed/final_rewards.csv")

In [10]:
df1

,name,projectID,creator,creatorID,homeUrl,currencySymbol,campaignGoal,fundsGathered,backersCount,campaignStart,campaignEnd,phaseLabel,enableBoardGameProperties,minPlayers,maxPlayers,minAge,playTime,playTimeUnit,fundedInSeconds,imageUrl,pledgeManagerSoftCloseDeadline,projectTags,originalType
0,We Played God - A Survival Miniatures Game,5787,Black Site Studios,5252,https://gamefound.com/creators/black-site-studios,$,10000.0,393538.44,1567,2025-06-17T14:30:00Z,2025-07-19T00:50:35.25Z,Pledge manager - Closed,False,NaN,NaN,NaN,NaN,0,628,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-02T15:00:00Z,"Exploration, Horror, Modern, Science Fiction, ...",1
1,CARNIVORE,6481,Buer Games,6737,https://gamefound.com/creators/buer-games,$,20000.0,247988.30,1075,2026-02-25T16:00:00Z,2026-03-31T15:57:23.953Z,Pledge manager - Closed,True,1.0,4.0,13.0,90.0,0,2716,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-01T14:00:00Z,"History, Strategy, Wargame, Action, Collectibl...",1
2,1809: Talavera,8024,Tactical Workshop,5141,https://gamefound.com/creators/tactical-workshop,$,7000.0,23091.47,215,2026-03-01T05:00:00Z,2026-04-01T05:00:00Z,Pledge manager - Closed,True,1.0,2.0,12.0,8.0,1,56442,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"History, Strategy, Wargame",1
3,Comber Cat,8225,Gamedolf Limited,8739,https://gamefound.com/creators/gamedolflimited,$,300.0,645.66,12,2026-02-02T13:00:00Z,2026-03-02T13:00:00Z,Pledge manager - Closed,True,2.0,5.0,8.0,15.0,0,2409627,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Card Game, Strategy, Party game, Family",1
4,Jano - A Pawsome Adventure,5995,aszaki,7221,https://gamefound.com/creators/aszaki,€,1000.0,4042.67,89,2026-01-16T12:00:00Z,2026-02-28T12:00:00Z,Pledge manager - Closed,True,2.0,6.0,8.0,20.0,0,14439,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-11T13:00:00Z,"Strategy, Resource management, Family, Worker ...",1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
483,Tectonia,2109,Hagen Behr,2703,https://gamefound.com/creators/hagen-behr,€,20000.0,8001.00,113,2022-07-05T18:00:00Z,2022-07-26T18:00:00Z,Crowdfunding - Unsuccessful,True,2.0,4.0,14.0,180.0,0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Strategy, Wargame, Dice Game, Area Control, Co...",1
484,Invasion Cards,2149,Lawrence Lyle,2742,https://gamefound.com/creators/lawrence-lyle,€,9800.0,70.00,2,2022-07-04T10:00:00Z,2022-08-03T21:00:00Z,Crowdfunding - Unsuccessful,True,2.0,4.0,5.0,25.0,0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Fantasy, Strategy, Humor",1
485,MOOGH,1919,Nuts! Publishing,2363,https://gamefound.com/creators/nuts-publishing,€,10000.0,6285.00,143,2022-04-26T16:00:00Z,2022-05-12T16:00:00Z,Crowdfunding - Unsuccessful,True,1.0,4.0,14.0,30.0,0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Dice Game, Multiplayer, Competitive, Campaign",1
486,Crossroads Inn: The Board Game,1143,Klabater,1510,https://gamefound.com/creators/klabater,€,20000.0,13420.63,158,2021-10-28T14:00:00Z,2021-11-30T15:00:00Z,Crowdfunding - Unsuccessful,True,2.0,4.0,12.0,120.0,0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Fantasy, Strategy, Terrain Building, Humor",1
487,Goldenstar: The Galactic Tournament,1325,Gindi,64,https://gamefound.com/creators/gindi,€,30000.0,10890.00,148,2021-10-05T16:00:00Z,2021-10-29T16:00:00Z,Crowdfunding - Unsuccessful,True,2.0,4.0,14.0,60.0,0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Science Fiction, Area Control, Deck Building",1

In [11]:
df1['originalType'].value_counts()

1    488
Name: originalType, dtype: int64

In [12]:
df1.loc[df1['creator']=="Gabe-Barrett"]

,name,projectID,creator,creatorID,homeUrl,currencySymbol,campaignGoal,fundsGathered,backersCount,campaignStart,campaignEnd,phaseLabel,enableBoardGameProperties,minPlayers,maxPlayers,minAge,playTime,playTimeUnit,fundedInSeconds,imageUrl,pledgeManagerSoftCloseDeadline,projectTags,originalType
8,Drawing Dead [Solo Game of the Month],6605,Gabe-Barrett,731,https://gamefound.com/creators/gabe-barrett,$,5000.0,83466.02,2010,2025-10-28T15:00:00Z,2025-11-15T06:15:03.567Z,Pledge manager - Closed,True,1.0,1.0,14.0,45.0,0,1444,https://imgcdn.gamefound.com/projectimage/proj...,NaN,Card Game,1
12,Mission: Drive [Solo Game of the Month],6435,Gabe-Barrett,731,https://gamefound.com/creators/gabe-barrett,$,5000.0,44548.95,1180,2025-09-30T15:00:00Z,2025-10-18T04:00:00Z,Pledge manager - Closed,True,1.0,1.0,14.0,45.0,0,3731,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Card Game, Strategy, Logical, Action, Video Ga...",1
27,Storybook Saga [Solo Game of the Month],6225,Gabe-Barrett,731,https://gamefound.com/creators/gabe-barrett,$,5000.0,96449.02,2546,2025-08-26T15:00:00Z,2025-09-13T04:00:00Z,Pledge manager - Closed,True,NaN,NaN,NaN,NaN,0,1267,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Fantasy, Card Game, Dice Game",1
35,Dice Commandos [Solo Game of the Month],6033,Gabe-Barrett,731,https://gamefound.com/creators/gabe-barrett,$,5000.0,71116.85,1825,2025-07-22T15:00:00Z,2025-08-09T04:37:13.41Z,Pledge manager - Closed,True,1.0,1.0,14.0,30.0,0,1609,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-09T23:00:00Z,"Card Game, Modern, Dice Game, Action",1
55,Dicemancy [Solo Game of the Month],5536,Gabe-Barrett,731,https://gamefound.com/creators/gabe-barrett,$,5000.0,90856.86,2383,2025-04-15T15:00:00Z,2025-05-03T04:44:52.423Z,Pledge manager - Closed,True,1.0,1.0,14.0,45.0,0,1052,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-09T16:00:00Z,"Card Game, Mythology, Dice Game",1
56,Knight Moves [Solo Game of the Month],5730,Gabe-Barrett,731,https://gamefound.com/creators/gabe-barrett,$,5000.0,55777.24,1492,2025-05-20T15:00:00Z,2025-06-06T05:22:03.3Z,Pledge manager - Closed,True,1.0,1.0,14.0,45.0,0,1653,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-15T14:00:00Z,"Card Game, Video Game Theme, Logical",1
71,Rome: Fate of an Empire (DELUXE) [Solo Game of...,5198,Gabe-Barrett,731,https://gamefound.com/creators/gabe-barrett,$,5000.0,185224.27,3273,2025-03-11T15:00:00Z,2025-03-29T05:06:11.233Z,Pledge manager - Closed,True,1.0,1.0,14.0,60.0,0,675,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-09T18:00:00Z,"Card Game, History, Strategy, Deck Building, E...",1
72,Paranormal [Solo Game of the Month],5197,Gabe-Barrett,731,https://gamefound.com/creators/gabe-barrett,$,5000.0,88246.33,2570,2025-02-11T16:00:00Z,2025-03-01T04:00:00Z,Pledge manager - Closed,True,1.0,2.0,14.0,45.0,0,1214,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-09T19:00:00Z,"Horror, Dice Game, Action",1
82,Action Packed Double Feature [Solo Game of the...,5104,Gabe-Barrett,731,https://gamefound.com/creators/gabe-barrett,$,5000.0,32954.47,926,2025-01-15T16:00:00Z,2025-02-01T05:00:00Z,Pledge manager - Closed,True,1.0,1.0,14.0,20.0,0,2787,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-13T16:00:00Z,Card Game,1
83,Small-Time Heroes [Solo Game of the Month],4983,Gabe-Barrett,731,https://gamefound.com/creators/gabe-barrett,$,5000.0,88843.43,2032,2024-12-17T16:00:00Z,2025-01-03T05:00:00Z,Pledge manager - Closed,True,1.0,2.0,NaN,40.0,0,1002,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-11T17:00:00Z,"Card Game, Fantasy, Cooperative",1
92,Mech Bunny [Solo Game of the Month],4777,Gabe-Barrett,731,https://gamefound.com/creators/gabe-barrett,$,5000.0,70312.30,2093,2024-11-19T16:00:00Z,2024-12-06T05:00:00Z,Pledge manager - Closed,True,1.0,1.0,NaN,40.0,0,1513,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-13T07:00:00Z,"Card Game, Action, Deck Building",1
117,Spooky Double Feature + Dieson Crusoe Reprint ...,4707,Gabe-Barrett,731,https://gamefound.com/creators/gabe-barrett,$,5000.0,52970.69,1429,2024-10-15T15:00:00Z,2024-11-01T04:59:00Z,Pledge manager - Closed,True,1.0,1.0,14.0,20.0,0,2091,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-16T05:00:00Z,"Card Game, Horror",1
120,Hunted: North Pole (2nd Edition) [Solo Game of...,4543,Gabe-Barrett,731,https://gamefound.com/creators/gabe-barrett,$,5000.0,22403.59,768,2024-09-17T15:00:00Z,2024-10-04T04:00:00Z,Pledge manager - Closed,True,1.0,2.0,14.0,20.0,0,5920,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-16T01:00:00Z,"Card Game, Dice Game, Adventure",1
126,7th Inning Stretch [Solo Game of the Month],4459,Gabe-Barrett,731,https://gamefound.com/creators/gabe-barrett,$,5000.0,41192.09,1416,2024-08-13T15:00:00Z,2024-08-30T04:59:00Z,Pledge manager - Closed,True,1.0,2.0,14.0,45.0,0,3718,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-12T13:00:00Z,"Card Game, Modern, Dice Game, Competitive",1
143,The Cursed Castle [Solo Game of the Month],4346,Gabe-Barrett,731,https://gamefound.com/creators/gabe-barrett,$,5000.0,67673.49,2326,2024-07-16T15:00:00Z,2024-08-02T04:59:00Z,Pledge manager - Closed,True,1.0,1.0,14.0,30.0,0,1379,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-10T06:00:00Z,"Card Game, Fantasy, Dice Game",1
152,Okinawa: The Last Battle of World War II [Solo...,4212,Gabe-Barrett,731,https://gamefound.com/creators/gabe-barrett,$,5000.0,54929.43,1842,2024-06-11T15:00:00Z,2024-06-28T04:00:00Z,Pledge manager - Closed,True,1.0,1.0,14.0,40.0,0,4005,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-15T20:00:00Z,"Card Game, Dice Game, Strategy, History",1
158,Hunted: Mining Colony 415 (2nd Edition) [Solo ...,4078,Gabe-Barrett,731,https://gamefound.com/creators/gabe-barrett,$,5000.0,61939.14,2239,2024-05-14T15:00:00Z,2024-05-31T04:59:00Z,Pledge manager - Closed,True,1.0,2.0,14.0,20.0,0,2313,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-14T10:00:00Z,"Card Game, Survival, Horror, Science Fiction, ...",1
170,Rome: Fate of an Empire [Solo Game of the Month],3997,Gabe-Barrett,731,https://gamefound.com/creators/gabe-barrett,$,5000.0,88961.75,2993,2024-04-09T15:00:00Z,2024-04-26T04:59:00Z,Pledge manager - Closed,True,1.0,1.0,14.0,60.0,0,1681,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-10T19:00:00Z,"Card Game, Strategy, History, Deck Building, C...",1
180,Dieson Crusoe [Solo Game of the Month],3745,Gabe-Barrett,731,https://gamefound.com/creators/gabe-barrett,$,5000.0,54509.76,1954,2024-02-13T16:00:00Z,2024-03-01T05:00:00Z,Pledge manager - Closed,True,1.0,1.0,12.0,30.0,0,3069,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-14T07:00:00Z,"Survival, Exploration, Dice Game, Adventure, W...",1
185,Hunted: Kobayashi Tower (2nd Edition) [Solo Ga...,3582,Gabe-Barrett,731,https://gamefound.com/creators/gabe-barrett,$,5000.0,46620.21,1793,2024-01-09T16:00:00Z,2024-01-26T05:59:00Z,Pledge manager - Closed,True,NaN,NaN,NaN,NaN,0,7462,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-14T02:00:00Z,"Card Game, Modern, Cooperative, Action, Dice Game",1
324,Hunted: Wode Ridge 2E [Solo Game of the Month],10156,Gabe-Barrett,731,https://gamefound.com/creators/gabe-barrett,$,5000.0,30498.67,925,2026-05-12T15:00:00Z,2026-05-30T04:10:00Z,Crowdfunding - Funded,True,1.0,2.0,14.0,45.0,0,2322,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Card Game, Adventure, Cooperative, Print and Play",1

In [13]:
df1.columns

Index(['name', 'projectID', 'creator', 'creatorID', 'homeUrl',
       'currencySymbol', 'campaignGoal', 'fundsGathered', 'backersCount',
       'campaignStart', 'campaignEnd', 'phaseLabel',
       'enableBoardGameProperties', 'minPlayers', 'maxPlayers', 'minAge',
       'playTime', 'playTimeUnit', 'fundedInSeconds', 'imageUrl',
       'pledgeManagerSoftCloseDeadline', 'projectTags', 'originalType'],
      dtype='object')

In [14]:
# creatorID -> 그 당시 몇개 만들었는지
# currencySymbol + campaignGoal, fundsGathered -> 단위 통일 하나 -> 조인 후 해야함
# campaignEnd- campaignStart -> 기간 만들고
# campaignStart 댓글 가지고 오는 용(시작 후 1주일?2주일)
# 'playTime', 'playTimeUnit' -> 1일경우에 시간으로 표시됨 하나로 통일
# pledgeManagerSoftCloseDeadline 있으면 1 없으면 0 -> 방치했나 신경썼나?
# projectTags -> 인코딩 ㅇㅇ

a_list = ['projectID',  'creatorID', 
       'currencySymbol', 'campaignGoal', 'fundsGathered', 'backersCount',
       'campaignStart', 'campaignEnd', 'phaseLabel',
       'enableBoardGameProperties', 'minPlayers', 'maxPlayers', 'minAge',
       'playTime', 'playTimeUnit', 'fundedInSeconds',
       'pledgeManagerSoftCloseDeadline', 'projectTags']

In [15]:
df1 = df1[a_list]
df1.head()

,projectID,creatorID,currencySymbol,campaignGoal,fundsGathered,backersCount,campaignStart,campaignEnd,phaseLabel,enableBoardGameProperties,minPlayers,maxPlayers,minAge,playTime,playTimeUnit,fundedInSeconds,pledgeManagerSoftCloseDeadline,projectTags
0,5787,5252,$,10000.0,393538.44,1567,2025-06-17T14:30:00Z,2025-07-19T00:50:35.25Z,Pledge manager - Closed,False,NaN,NaN,NaN,NaN,0,628,2026-06-02T15:00:00Z,"Exploration, Horror, Modern, Science Fiction, ..."
1,6481,6737,$,20000.0,247988.30,1075,2026-02-25T16:00:00Z,2026-03-31T15:57:23.953Z,Pledge manager - Closed,True,1.0,4.0,13.0,90.0,0,2716,2026-06-01T14:00:00Z,"History, Strategy, Wargame, Action, Collectibl..."
2,8024,5141,$,7000.0,23091.47,215,2026-03-01T05:00:00Z,2026-04-01T05:00:00Z,Pledge manager - Closed,True,1.0,2.0,12.0,8.0,1,56442,NaN,"History, Strategy, Wargame"
3,8225,8739,$,300.0,645.66,12,2026-02-02T13:00:00Z,2026-03-02T13:00:00Z,Pledge manager - Closed,True,2.0,5.0,8.0,15.0,0,2409627,NaN,"Card Game, Strategy, Party game, Family"
4,5995,7221,€,1000.0,4042.67,89,2026-01-16T12:00:00Z,2026-02-28T12:00:00Z,Pledge manager - Closed,True,2.0,6.0,8.0,20.0,0,14439,2026-06-11T13:00:00Z,"Strategy, Resource management, Family, Worker ..."

In [9]:
df1['previous_campaigns_count'].value_counts()

0     346
1      65
2      32
3      11
4       7
5       3
6       3
7       3
8       3
9       2
11      2
10      2
12      1
15      1
13      1
14      1
16      1
17      1
18      1
19      1
20      1
Name: previous_campaigns_count, dtype: int64

In [13]:
df1['projectTags'].value_counts()

Card Game                                                                   7
History, Wargame, Strategy, Area Control, Asymmetric                        2
Card Game, Strategy                                                         2
Wargame, Strategy, History                                                  2
History, Strategy, Wargame                                                  2
                                                                           ..
Strategy, Dice Game, Economic                                               1
Science Fiction, History, RPG, Cooperative, Multiplayer, Campaign, TTRPG    1
Card Game, Strategy, Humor, Educational, Asymmetric, Competitive, Family    1
Card Game, Survival, Horror, Science Fiction, Adventure, Dexterity          1
Science Fiction, Area Control, Deck Building                                1
Name: projectTags, Length: 477, dtype: int64

In [20]:
df1.loc[df1['previous_campaigns_count']==1]

,projectID,creatorID,currencySymbol,campaignGoal,fundsGathered,backersCount,campaignStart,campaignEnd,phaseLabel,enableBoardGameProperties,minPlayers,maxPlayers,minAge,playTime,playTimeUnit,fundedInSeconds,pledgeManagerSoftCloseDeadline,projectTags,previous_campaigns_count
2,8024,5141,$,7000.0,23091.47,215,2026-03-01 05:00:00+00:00,2026-04-01T05:00:00Z,Pledge manager - Closed,True,1.0,2.0,12.0,8.0,1,56442,NaN,"History, Strategy, Wargame",1
7,5097,3528,€,18000.0,37305.79,440,2025-09-10 14:00:00+00:00,2025-10-08T14:22:22.747Z,Pledge manager - Closed,True,2.0,7.0,8.0,15.0,0,1994311,NaN,"Card Game, Game Components, Set Collection, Mu...",1
9,5715,3657,C$,1000.0,2122.91,38,2025-12-20 05:00:00+00:00,2026-01-20T05:01:00Z,Pledge manager - Closed,True,2.0,6.0,7.0,30.0,0,116429,2026-05-14T16:00:00Z,"Card Game, Multiplayer, Party game, Dice Game,...",1
33,5180,3906,€,28000.0,193765.78,1448,2025-07-31 15:00:00+00:00,2025-08-23T18:59:39.91Z,Pledge manager - Closed,True,1.0,6.0,14.0,90.0,0,11430,2026-06-10T12:00:00Z,"Exploration, Science Fiction, Modern, Horror, ...",1
42,5446,4233,€,5000.0,23813.80,370,2025-07-24 14:00:00+00:00,2025-08-05T22:10:00Z,Pledge manager - Closed,True,1.0,4.0,12.0,45.0,0,40706,2026-05-31T22:00:00Z,"Strategy, History",1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
418,5609,2742,€,10000.0,204.00,4,2025-05-07 21:00:00+00:00,2025-07-06T21:00:00Z,Crowdfunding - Unsuccessful,True,2.0,24.0,16.0,35.0,0,0,NaN,"Fantasy, Card Game, Survival, Horror, History,...",1
419,4618,4098,€,14000.0,2417.68,63,2025-05-04 10:00:00+00:00,2025-05-25T10:00:00Z,Crowdfunding - Unsuccessful,True,1.0,4.0,14.0,120.0,0,0,NaN,"Fantasy, Card Game, Survival, RPG, Adventure, ...",1
427,5047,3141,$,18900.0,8053.39,105,2025-03-21 17:00:00+00:00,2025-05-20T16:00:00Z,Crowdfunding - Unsuccessful,True,1.0,2.0,14.0,360.0,0,0,NaN,"Wargame, Strategy, History",1
431,5059,5038,$,10000.0,861.20,13,2025-03-04 14:00:00+00:00,2025-04-01T01:00:00Z,Crowdfunding - Unsuccessful,True,1.0,3.0,14.0,90.0,0,0,NaN,"Strategy, Horror, Science Fiction, Multiplayer...",1
441,3546,2797,€,10000.0,2421.09,23,2024-10-08 14:00:00+00:00,2024-11-10T13:00:00Z,Crowdfunding - Unsuccessful,True,2.0,4.0,18.0,30.0,0,0,NaN,"Card Game, Humor, Party game",1

In [8]:
df2

,main_name,projectID,anchorRelativeUrl,price,isDiscounted,effectivePrice,isFeatured,purchasedCopiesCount,backgroundUrl,installmentCost,installmentMinPayment,hasLimitedStock,productCanBePurchased,productID,remainingStockLimit
0,We Played God - A Survival Miniatures Game,5787,core-rules-physical-pdf-80323,60.0,False,60.0,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,75.0,False,False,80323,NaN
1,We Played God - A Survival Miniatures Game,5787,eden-visitor-digital-pdfs-digital-survivor-stl...,62.0,False,62.0,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,75.0,False,False,81221,NaN
2,We Played God - A Survival Miniatures Game,5787,eden-visitor-physical-core-rules-survivor-mini...,124.0,True,110.0,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,75.0,False,False,80326,NaN
3,We Played God - A Survival Miniatures Game,5787,eden-hacker-digital-all-in-81322,147.0,True,132.0,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,75.0,False,False,81322,NaN
4,We Played God - A Survival Miniatures Game,5787,eden-visitor-deluxe-physical-core-rules-surviv...,159.0,True,145.0,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,75.0,False,False,81320,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2102,Crossroads Inn: The Board Game,1143,6-x-crossroads-inn-the-board-game-standard-edi...,300.0,True,264.0,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,19155,NaN
2103,Goldenstar: The Galactic Tournament,1325,champion-gameplay-all-in-18047,72.0,False,72.0,True,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,18047,NaN
2104,Goldenstar: The Galactic Tournament,1325,goldenstar-core-pledge-17700,43.0,False,43.0,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,17700,NaN
2105,Goldenstar: The Galactic Tournament,1325,challenger-18042,69.0,False,69.0,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,18042,NaN
2106,Goldenstar: The Galactic Tournament,1325,legend-all-in-18052,97.0,False,97.0,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,18052,NaN

In [49]:
df2['remainingStockLimit'].value_counts()

remainingStockLimit
0.0      217
1.0       26
100.0     13
2.0       12
5.0       10
        ...
48.0       1
62.0       1
418.0      1
837.0      1
498.0      1
Name: count, Length: 121, dtype: int64

In [51]:
df2.loc[df2["remainingStockLimit"]==250]

,main_name,projectID,anchorRelativeUrl,price,isDiscounted,effectivePrice,isFeatured,purchasedCopiesCount,backgroundUrl,installmentCost,installmentMinPayment,hasLimitedStock,productCanBePurchased,productID,remainingStockLimit
1662,Nova Aetas Renaissance - The Last chance,3459,become-a-hero-north-america-hub-45520,389.0,True,299.0,False,0,https://imgcdn.gamefound.com/productimage/proj...,99.666667,200.0,True,False,45520,250.0
2003,Blight Seas Fleet,3775,blight-seas-fleet-physical-starter-set-4-copie...,200.0,True,160.0,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,49638,250.0

In [17]:

len(set(df2.loc[df2["isFeatured"]==True]["main_name"]))

443

In [22]:
len(set(df2['projectID']))

484

In [18]:
df2.loc[df2["isFeatured"]==True]["main_name"].value_counts()

main_name
Lords of Ragnarok                                                   10
Monster Invasion                                                     5
FlickFleet: Xeno Wars                                                2
soccerone                                                            2
Pandemonium Estate                                                   2
                                                                    ..
The LAB                                                              1
Hunted: Mining Colony 415 (2nd Edition) [Solo Game of the Month]     1
Steam Power                                                          1
Tabletop Inc.                                                        1
Goldenstar: The Galactic Tournament                                  1
Name: count, Length: 443, dtype: int64

In [23]:
df2.loc[df2["main_name"]=="Goldenstar: The Galactic Tournament"]

,main_name,projectID,anchorRelativeUrl,price,isDiscounted,effectivePrice,isFeatured,purchasedCopiesCount,backgroundUrl,installmentCost,installmentMinPayment,hasLimitedStock,productCanBePurchased,productID,remainingStockLimit
2103,Goldenstar: The Galactic Tournament,1325,champion-gameplay-all-in-18047,72.0,False,72.0,True,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,18047,NaN
2104,Goldenstar: The Galactic Tournament,1325,goldenstar-core-pledge-17700,43.0,False,43.0,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,17700,NaN
2105,Goldenstar: The Galactic Tournament,1325,challenger-18042,69.0,False,69.0,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,18042,NaN
2106,Goldenstar: The Galactic Tournament,1325,legend-all-in-18052,97.0,False,97.0,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,18052,NaN

In [9]:
df2.columns

Index(['main_name', 'projectID', 'anchorRelativeUrl', 'price', 'isDiscounted',
       'effectivePrice', 'isFeatured', 'purchasedCopiesCount', 'backgroundUrl',
       'installmentCost', 'installmentMinPayment', 'hasLimitedStock',
       'productCanBePurchased', 'productID', 'remainingStockLimit'],
      dtype='object')

In [52]:
# price 조인하고 처리해야함 단위 모름

b_list = ['projectID',  'price', 'isDiscounted',
       'effectivePrice', 'installmentMinPayment']

In [37]:
list(set(df2['projectID']))

[6153,
 2057,
 8203,
 2063,
 2065,
 4120,
 2072,
 4126,
 6176,
 8225,
 2081,
 4134,
 6184,
 2098,
 6194,
 2108,
 2109,
 4164,
 8265,
 6221,
 4174,
 8271,
 6225,
 8277,
 2135,
 4188,
 6236,
 4189,
 2144,
 2149,
 2152,
 8302,
 6255,
 4212,
 2181,
 6277,
 4234,
 4235,
 4240,
 2200,
 2207,
 2213,
 2217,
 2219,
 2220,
 2225,
 6321,
 2235,
 2236,
 2242,
 2245,
 2246,
 2264,
 222,
 2275,
 8420,
 6374,
 2279,
 6378,
 6379,
 6381,
 4340,
 2295,
 4346,
 2304,
 2311,
 2314,
 2315,
 4364,
 4365,
 4368,
 6419,
 8475,
 6435,
 4399,
 4400,
 2352,
 6456,
 2362,
 4410,
 4412,
 4414,
 2371,
 8515,
 8517,
 2378,
 8526,
 6481,
 4434,
 2387,
 2389,
 2390,
 6486,
 4439,
 4440,
 2404,
 2407,
 2408,
 4457,
 4459,
 6510,
 6516,
 4475,
 6528,
 2435,
 2436,
 6544,
 4504,
 2460,
 4514,
 6562,
 6571,
 2486,
 2494,
 4543,
 6595,
 6605,
 2512,
 2518,
 4566,
 2519,
 2525,
 6626,
 6631,
 2536,
 4590,
 4591,
 4594,
 2554,
 6650,
 4609,
 6657,
 4618,
 4621,
 2573,
 2575,
 6676,
 4637,
 4639,
 4642,
 4649,
 4659,
 4664,
 4672,
 2635,
 2640,
 2643,
 2646,
 6743,
 4707,
 6758,
 2671,
 6773,
 4728,
 2684,
 4737,
 2689,
 4740,
 2702,
 4772,
 2728,
 4777,
 2729,
 4779,
 2735,
 4784,
 4804,
 2757,
 2758,
 2763,
 2771,
 6867,
 2782,
 2790,
 2793,
 4845,
 4849,
 2802,
 2801,
 2813,
 2816,
 6913,
 769,
 2823,
 4874,
 4879,
 2832,
 6941,
 2847,
 2850,
 806,
 2856,
 2857,
 4906,
 4916,
 6967,
 2874,
 2875,
 2879,
 2882,
 2893,
 4944,
 2905,
 2909,
 862,
 4973,
 2932,
 887,
 4983,
 2935,
 889,
 2939,
 2942,
 5009,
 2967,
 2969,
 2972,
 2977,
 5030,
 2983,
 2984,
 5041,
 2997,
 5047,
 3002,
 954,
 3006,
 3007,
 5059,
 5060,
 5064,
 3016,
 975,
 5077,
 5082,
 5084,
 5090,
 5097,
 5104,
 5108,
 3066,
 5125,
 1032,
 3082,
 5133,
 5142,
 1060,
 3112,
 1066,
 3119,
 3124,
 3125,
 1078,
 1081,
 5180,
 3135,
 3136,
 3144,
 5197,
 5198,
 5199,
 3151,
 1103,
 5202,
 3154,
 3161,
 1114,
 5211,
 3166,
 3175,
 3176,
 3183,
 5234,
 1143,
 1145,
 1148,
 5258,
 3211,
 5261,
 3215,
 5275,
 3232,
 5281,
 5284,
 3236,
 3244,
 3248,
 3252,
 3261,
 3273,
 5325,
 3278,
 3282,
 3285,
 1248,
 3298,
 5349,
 5357,
 1263,
 3313,
 1268,
 5386,
 3339,
 3340,
 5395,
 3347,
 1301,
 5401,
 3360,
 3365,
 1318,
 1320,
 1325,
 5423,
 5429,
 3383,
 1342,
 1348,
 5446,
 3402,
 5452,
 5454,
 5463,
 3425,
 3444,
 1398,
 3453,
 1405,
 3457,
 3459,
 3478,
 1430,
 3484,
 1438,
 5536,
 1442,
 3493,
 1449,
 3499,
 3503,
 3506,
 1460,
 3515,
 5563,
 1476,
 5584,
 3539,
 3546,
 3547,
 9693,
 3554,
 5609,
 5625,
 3582,
 1539,
 3588,
 3592,
 5640,
 5644,
 3612,
 3617,
 3618,
 5669,
 3623,
 5676,
 1599,
 5715,
 5719,
 3678,
 5730,
 3685,
 5737,
 5738,
 1643,
 3692,
 5739,
 5740,
 3695,
 1661,
 3711,
 3723,
 3724,
 3726,
 3731,
 3734,
 5787,
 1691,
 3745,
 3748,
 5802,
 3755,
 3766,
 1720,
 5817,
 1721,
 3771,
 5820,
 1725,
 3775,
 5838,
 3797,
 3803,
 1755,
 3810,
 5862,
 3815,
 1767,
 3818,
 3828,
 3830,
 1782,
 1790,
 5887,
 3844,
 5894,
 3847,
 3848,
 3849,
 1799,
 1804,
 5900,
 5906,
 5918,
 5920,
 3877,
 1837,
 3890,
 3895,
 3897,
 1851,
 10044,
 1856,
 3906,
 5956,
 5958,
 5969,
 3922,
 5971,
 8024,
 1888,
 3937,
 3941,
 1893,
 1897,
 5995,
 3949,
 6007,
 3960,
 1919,
 1926,
 1927,
 6026,
 6033,
 3988,
 6039,
 8091,
 3997,
 4003,
 4007,
 10156,
 4013,
 6064,
 4018,
 1977,
 4034,
 1986,
 8130,
 4037,
 1987,
 1991,
 6088,
 6087,
 4042,
 2002,
 6099,
 2005,
 8150,
 4065,
 6117,
 2023,
 4078,
 2032,
 4088,
 4093]

In [43]:
list(df2['projectID'].drop_duplicates())[99]

3499

In [27]:
for i in df1["projectID"]:
    if i not in list(set(df2['projectID'])):
        print(i)

4358
7001
5535
5043

In [53]:
df2[b_list]

      projectID  price  isDiscounted  effectivePrice  installmentMinPayment
0          5787   60.0         False            60.0                   75.0
1          5787   62.0         False            62.0                   75.0
2          5787  124.0          True           110.0                   75.0
3          5787  147.0          True           132.0                   75.0
4          5787  159.0          True           145.0                   75.0
...         ...    ...           ...             ...                    ...
2102       1143  300.0          True           264.0                    NaN
2103       1325   72.0         False            72.0                    NaN
2104       1325   43.0         False            43.0                    NaN
2105       1325   69.0         False            69.0                    NaN
2106       1325   97.0         False            97.0                    NaN

[2107 rows x 5 columns]

조인 후 실행

In [ ]:
final_df = pd.merge(df1, df2, on='projectID', how='left')

In [ ]:
df1['campaignStart'] = pd.to_datetime(df1['campaignStart'])
df1['campaignEnd'] = pd.to_datetime(df1['campaignEnd'])


# creatorID -> 그 당시 몇개 만들었는지
final_df = final_df.sort_values(by='campaignStart')
final_df['previous_campaigns_count'] = final_df.groupby('creatorID').cumcount()
final_df = final_df.sort_index()

# 프로젝트 진행 기간 계산
final_df['duration_days'] = (final_df['campaignEnd'] - final_df['campaignStart']).dt.days

# 댓글 수집 기준일 계산 (시작일로부터 1주일, 2주일 뒤) 댓글 조인 후 날짜 잘라도?
#final_df['comment_target_1w'] = final_df['campaignStart'] + pd.Timedelta(days=7)

# playTime 단위 통일 (playTimeUnit이 1이면 시간 단위 -> 분으로 변환)
final_df.loc[final_df['playTimeUnit'] == 1, 'playTime'] = final_df['playTime'] * 60

# pledgeManagerSoftCloseDeadline 존재 여부 (방치 여부/관리 척도)
final_df['softclose'] = final_df['pledgeManagerSoftCloseDeadline'].notna().astype(int)

# projectTags 원핫인코딩
tags_encoded = final_df['projectTags'].fillna('').str.get_dummies(sep=', ')
final_df = pd.concat([final_df, tags_encoded], axis=1)

# final_df = final_df.drop(columns=['playTimeUnit', 'pledgeManagerSoftCloseDeadline', 'projectTags'])

In [18]:
tags_encoded.columns.tolist()

['4X',
 'AR Next',
 'ARNext26',
 'Action',
 'Adventure',
 'Area Control',
 'Asymmetric',
 'Campaign',
 'Card Game',
 'Cats',
 'Civilization',
 'Collectible',
 'Collectible Models',
 'Competitive',
 'Cooperative',
 'Deck Building',
 'Deduction',
 'Dexterity',
 'Dice Game',
 'Digital',
 'Economic',
 'Educational',
 'Exploration',
 'Family',
 'Fantasy',
 'Feast',
 'First-Timers',
 'Game Components',
 'History',
 'Horror',
 'Humor',
 'Legacy',
 'Logical',
 'MOBA',
 'Major Creators',
 'Media',
 'Modern',
 'Multiplayer',
 'Mythology',
 'Narrative',
 'OctoberFeast25',
 'Paint',
 'Party game',
 'Political',
 'Print and Play',
 'RPG',
 'Racing',
 'Reprints',
 'Resource management',
 'Science Fiction',
 'Set Collection',
 'Sport',
 'Strategy',
 'Survival',
 'TTRPG',
 'Terrain Building',
 'Tower Defense',
 'Video Game',
 'Video Game Theme',
 'Wargame',
 'WinterFeast2026',
 'Worker placement',
 'dinotuesday']